/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/user/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/user/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/common/src/directives/ng_if';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/validators';
import * as import22 from '@angular/forms/src/validators';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/forms/src/directives/ng_form';
import * as import28 from '@angular/forms/src/directives/control_container';
export class Wrapper_LoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.LoginComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginComponent>;
  _LoginComponent_0_3:Wrapper_LoginComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent_Host0,renderType_LoginComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LoginComponent0(this.viewUtils,this,0,this._el_0);
    this._LoginComponent_0_3 = new Wrapper_LoginComponent(this.injectorGet(import8.AuthService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex));
    this.compView_0.create(this._LoginComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LoginComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginComponentNgFactory:import7.ComponentFactory<import0.LoginComponent> = new import7.ComponentFactory<import0.LoginComponent>('ng-component',View_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = ['em[_ngcontent-%COMP%] {float:right; color:#E05C65; padding-left:10px;}'];
var renderType_LoginComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_LoginComponent,{});
export class View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import10.Wrapper_NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import11.Wrapper_NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import12.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import13.Wrapper_NgIf;
  _text_15:any;
  _el_16:any;
  _DefaultValueAccessor_16_3:import14.Wrapper_DefaultValueAccessor;
  _RequiredValidator_16_4:import15.Wrapper_RequiredValidator;
  _NG_VALIDATORS_16_5:any[];
  _NG_VALUE_ACCESSOR_16_6:any[];
  _NgModel_16_7:import16.Wrapper_NgModel;
  _NgControl_16_8:any;
  _NgControlStatus_16_9:import11.Wrapper_NgControlStatus;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _vc_24:import12.ViewContainer;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import13.Wrapper_NgIf;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import14.Wrapper_DefaultValueAccessor;
  _RequiredValidator_26_4:import15.Wrapper_RequiredValidator;
  _NG_VALIDATORS_26_5:any[];
  _NG_VALUE_ACCESSOR_26_6:any[];
  _NgModel_26_7:import16.Wrapper_NgModel;
  _NgControl_26_8:any;
  _NgControlStatus_26_9:import11.Wrapper_NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _vc_39:import12.ViewContainer;
  _TemplateRef_39_5:any;
  _NgIf_39_6:import13.Wrapper_NgIf;
  _text_40:any;
  _text_41:any;
  /*private*/ _expr_68:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent0,renderType_LoginComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_68 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Login',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'form',new import3.InlineArray4(4,'autocomplete','off','novalidate',''),(null as any));
    this._NgForm_7_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3.context;
    this._NgControlStatusGroup_7_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'label',new import3.InlineArray2(2,'for','userName'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'User Name:',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_14 = new import12.ViewContainer(14,9,this,this._anchor_14);
    this._TemplateRef_14_5 = new import17.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import13.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_9,'input',new import3.InlineArray16(12,'class','form-control','id','userName','name','userName','placeholder','User Name...','required','','type','text'),(null as any));
    this._DefaultValueAccessor_16_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_16));
    this._RequiredValidator_16_4 = new import15.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_16_5 = [this._RequiredValidator_16_4.context];
    this._NG_VALUE_ACCESSOR_16_6 = [this._DefaultValueAccessor_16_3.context];
    this._NgModel_16_7 = new import16.Wrapper_NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_16_5,(null as any),this._NG_VALUE_ACCESSOR_16_6);
    this._NgControl_16_8 = this._NgModel_16_7.context;
    this._NgControlStatus_16_9 = new import11.Wrapper_NgControlStatus(this._NgControl_16_8);
    this._text_17 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'label',new import3.InlineArray2(2,'for','password'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Password:',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_24 = new import12.ViewContainer(24,19,this,this._anchor_24);
    this._TemplateRef_24_5 = new import17.TemplateRef_(this,24,this._anchor_24);
    this._NgIf_24_6 = new import13.Wrapper_NgIf(this._vc_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_19,'input',new import3.InlineArray16(12,'class','form-control','id','password','name','password','placeholder','Password...','required','','type','password'),(null as any));
    this._DefaultValueAccessor_26_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_26));
    this._RequiredValidator_26_4 = new import15.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_26_5 = [this._RequiredValidator_26_4.context];
    this._NG_VALUE_ACCESSOR_26_6 = [this._DefaultValueAccessor_26_3.context];
    this._NgModel_26_7 = new import16.Wrapper_NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_26_5,(null as any),this._NG_VALUE_ACCESSOR_26_6);
    this._NgControl_26_8 = this._NgModel_26_7.context;
    this._NgControlStatus_26_9 = new import11.Wrapper_NgControlStatus(this._NgControl_26_8);
    this._text_27 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_7,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_29,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Login',(null as any));
    this._text_32 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_7,'button',new import3.InlineArray4(4,'class','btn btn-default','type','button'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Cancel',(null as any));
    this._text_35 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_36 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_5,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._vc_39 = new import12.ViewContainer(39,5,this,this._anchor_39);
    this._TemplateRef_39_5 = new import17.TemplateRef_(this,39,this._anchor_39);
    this._NgIf_39_6 = new import13.Wrapper_NgIf(this._vc_39.vcRef,this._TemplateRef_39_5);
    this._text_40 = this.renderer.createText(this._el_5,'\n',(null as any));
    this._text_41 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_7));
    this._NgForm_7_3.subscribe(this,this.eventHandler(this.handleEvent_7),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray8(6,'ngModel',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_16));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray8(6,'ngModel',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_26));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray4(4,'mouseenter',(null as any),'mouseleave',(null as any)),this.eventHandler(this.handleEvent_29));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_33));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._text_41
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import19.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import20.DefaultValueAccessor) && (16 === requestNodeIndex))) { return this._DefaultValueAccessor_16_3.context; }
    if (((token === import21.RequiredValidator) && (16 === requestNodeIndex))) { return this._RequiredValidator_16_4.context; }
    if (((token === import22.NG_VALIDATORS) && (16 === requestNodeIndex))) { return this._NG_VALIDATORS_16_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_6; }
    if (((token === import24.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_7.context; }
    if (((token === import25.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_8; }
    if (((token === import26.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_9.context; }
    if (((token === import17.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import19.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6.context; }
    if (((token === import20.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3.context; }
    if (((token === import21.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4.context; }
    if (((token === import22.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_6; }
    if (((token === import24.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_7.context; }
    if (((token === import25.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_8; }
    if (((token === import26.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_9.context; }
    if (((token === import27.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgForm_7_3.context; }
    if (((token === import28.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._ControlContainer_7_4; }
    if (((token === import26.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgControlStatusGroup_7_5.context; }
    if (((token === import17.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import19.NgIf) && (39 === requestNodeIndex))) { return this._NgIf_39_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._NgControlStatusGroup_7_5.ngDoCheck(this,this._el_7,throwOnChange);
    var tmp_14_0_0_0:any = (null as any);
    const currVal_14_0_0:any = ((((tmp_14_0_0_0 = this._NgForm_7_3.context.form.get('userName')) == null)? (null as any): tmp_14_0_0_0.invalid) && ((((tmp_14_0_0_0 = this._NgForm_7_3.context.form.get('userName')) == null)? (null as any): tmp_14_0_0_0.touched) || this.context.mouseoverLogin));
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    this._DefaultValueAccessor_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_16_1_0:any = '';
    this._RequiredValidator_16_4.check_required(currVal_16_1_0,throwOnChange,false);
    this._RequiredValidator_16_4.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_16_2_0:any = 'userName';
    this._NgModel_16_7.check_name(currVal_16_2_0,throwOnChange,false);
    this._NgModel_16_7.ngDoCheck(this,this._el_16,throwOnChange);
    this._NgControlStatus_16_9.ngDoCheck(this,this._el_16,throwOnChange);
    var tmp_24_0_0_0:any = (null as any);
    const currVal_24_0_0:any = ((((tmp_24_0_0_0 = this._NgForm_7_3.context.form.get('password')) == null)? (null as any): tmp_24_0_0_0.invalid) && ((((tmp_24_0_0_0 = this._NgForm_7_3.context.form.get('password')) == null)? (null as any): tmp_24_0_0_0.touched) || this.context.mouseoverLogin));
    this._NgIf_24_6.check_ngIf(currVal_24_0_0,throwOnChange,false);
    this._NgIf_24_6.ngDoCheck(this,this._anchor_24,throwOnChange);
    this._DefaultValueAccessor_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_26_1_0:any = '';
    this._RequiredValidator_26_4.check_required(currVal_26_1_0,throwOnChange,false);
    this._RequiredValidator_26_4.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_26_2_0:any = 'password';
    this._NgModel_26_7.check_name(currVal_26_2_0,throwOnChange,false);
    this._NgModel_26_7.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_9.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_39_0_0:any = this.context.loginInvalid;
    this._NgIf_39_6.check_ngIf(currVal_39_0_0,throwOnChange,false);
    this._NgIf_39_6.ngDoCheck(this,this._anchor_39,throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_24.detectChangesInNestedViews(throwOnChange);
    this._vc_39.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_7_5.checkHost(this,this,this._el_7,throwOnChange);
    this._RequiredValidator_16_4.checkHost(this,this,this._el_16,throwOnChange);
    this._NgControlStatus_16_9.checkHost(this,this,this._el_16,throwOnChange);
    this._RequiredValidator_26_4.checkHost(this,this,this._el_26,throwOnChange);
    this._NgControlStatus_26_9.checkHost(this,this,this._el_26,throwOnChange);
    const currVal_68:any = this._NgForm_7_3.context.invalid;
    if (import3.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementProperty(this._el_30,'disabled',currVal_68);
      this._expr_68 = currVal_68;
    }
  }
  destroyInternal():void {
    this._vc_14.destroyNestedViews();
    this._vc_24.destroyNestedViews();
    this._vc_39.destroyNestedViews();
    this._NgModel_16_7.ngOnDestroy();
    this._NgModel_26_7.ngOnDestroy();
    this._NgForm_7_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 14)) { return new View_LoginComponent1(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 24)) { return new View_LoginComponent2(this.viewUtils,this,24,this._anchor_24,this._vc_24); }
    if ((nodeIndex == 39)) { return new View_LoginComponent3(this.viewUtils,this,39,this._anchor_39,this._vc_39); }
    return (null as any);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_7_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.login(this._NgForm_7_3.context.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_16_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModel')) {
      const pd_sub_0:any = ((<any>this.context.userName) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_26_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModel')) {
      const pd_sub_0:any = ((<any>this.context.password) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'mouseenter')) {
      const pd_sub_0:any = ((<any>(this.context.mouseoverLogin = true)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'mouseleave')) {
      const pd_sub_1:any = ((<any>(this.context.mouseoverLogin = false)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.cancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_LoginComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_LoginComponent1,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_LoginComponent2,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_LoginComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_LoginComponent3,renderType_LoginComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Invalid Login Info',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}