/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/user/profile.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../app/user/auth.service';
import * as import10 from '../../../app/common/toastr.service';
import * as import11 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import18 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import19 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/common/src/directives/ng_if';
import * as import23 from '@angular/forms/src/directives/default_value_accessor';
import * as import24 from '@angular/forms/src/directives/control_value_accessor';
import * as import25 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import26 from '@angular/forms/src/directives/ng_control';
import * as import27 from '@angular/forms/src/directives/ng_control_status';
import * as import28 from '@angular/common/src/directives/ng_class';
import * as import29 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import30 from '@angular/forms/src/directives/control_container';
export class Wrapper_ProfileComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ProfileComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.ProfileComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ProfileComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ProfileComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ProfileComponent>;
  _ProfileComponent_0_3:Wrapper_ProfileComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ProfileComponent_Host0,renderType_ProfileComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ProfileComponent0(this.viewUtils,this,0,this._el_0);
    this._ProfileComponent_0_3 = new Wrapper_ProfileComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.AuthService,this.parentIndex),this.injectorGet(import10.TOASTR_TOKEN,this.parentIndex));
    this.compView_0.create(this._ProfileComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ProfileComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ProfileComponent) && (0 === requestNodeIndex))) { return this._ProfileComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ProfileComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ProfileComponentNgFactory:import7.ComponentFactory<import0.ProfileComponent> = new import7.ComponentFactory<import0.ProfileComponent>('ng-component',View_ProfileComponent_Host0,import0.ProfileComponent);
const styles_ProfileComponent:any[] = ['em[_ngcontent-%COMP%] {float:right; color:#E05C65; padding-left:10px;}\n    .error[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {background-color:#E3C3C5;}\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-webkit-input-placeholder { color: #999; } \n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:-moz-placeholder { color: #999; }\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-moz-placeholder { color: #999; }\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:ms-input-placeholder  { color: #999; }'];
var renderType_ProfileComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ProfileComponent,{});
export class View_ProfileComponent0 extends import1.AppView<import0.ProfileComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _FormGroupDirective_9_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_9_4:any;
  _NgControlStatusGroup_9_5:import12.Wrapper_NgControlStatusGroup;
  _text_10:any;
  _el_11:any;
  _NgClass_11_3:import13.Wrapper_NgClass;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import14.ViewContainer;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import15.Wrapper_NgIf;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import14.ViewContainer;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import15.Wrapper_NgIf;
  _text_19:any;
  _el_20:any;
  _DefaultValueAccessor_20_3:import16.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_20_4:any[];
  _FormControlName_20_5:import17.Wrapper_FormControlName;
  _NgControl_20_6:any;
  _NgControlStatus_20_7:import12.Wrapper_NgControlStatus;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _NgClass_23_3:import13.Wrapper_NgClass;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _vc_28:import14.ViewContainer;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import15.Wrapper_NgIf;
  _text_29:any;
  _el_30:any;
  _DefaultValueAccessor_30_3:import16.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_30_4:any[];
  _FormControlName_30_5:import17.Wrapper_FormControlName;
  _NgControl_30_6:any;
  _NgControlStatus_30_7:import12.Wrapper_NgControlStatus;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _map_68:any;
  _map_69:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ProfileComponent0,renderType_ProfileComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_68 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_69 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Edit Your Profile ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-md-4'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'form',new import3.InlineArray4(4,'autocomplete','off','novalidate',''),(null as any));
    this._FormGroupDirective_9_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_9_4 = this._FormGroupDirective_9_3.context;
    this._NgControlStatusGroup_9_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_9_4);
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_11_3 = new import13.Wrapper_NgClass(this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import19.KeyValueDiffers,this.parentIndex),new import20.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'label',new import3.InlineArray2(2,'for','firstName'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'First Name:',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._vc_16 = new import14.ViewContainer(16,11,this,this._anchor_16);
    this._TemplateRef_16_5 = new import21.TemplateRef_(this,16,this._anchor_16);
    this._NgIf_16_6 = new import15.Wrapper_NgIf(this._vc_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._vc_18 = new import14.ViewContainer(18,11,this,this._anchor_18);
    this._TemplateRef_18_5 = new import21.TemplateRef_(this,18,this._anchor_18);
    this._NgIf_18_6 = new import15.Wrapper_NgIf(this._vc_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_11,'input',new import3.InlineArray16(10,'class','form-control','formControlName','firstName','id','firstName','placeholder','First Name...','type','text'),(null as any));
    this._DefaultValueAccessor_20_3 = new import16.Wrapper_DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_20));
    this._NG_VALUE_ACCESSOR_20_4 = [this._DefaultValueAccessor_20_3.context];
    this._FormControlName_20_5 = new import17.Wrapper_FormControlName(this._ControlContainer_9_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_20_4);
    this._NgControl_20_6 = this._FormControlName_20_5.context;
    this._NgControlStatus_20_7 = new import12.Wrapper_NgControlStatus(this._NgControl_20_6);
    this._text_21 = this.renderer.createText(this._el_11,'\n      ',(null as any));
    this._text_22 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_23_3 = new import13.Wrapper_NgClass(this.parentView.injectorGet(import18.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import19.KeyValueDiffers,this.parentIndex),new import20.ElementRef(this._el_23),this.renderer);
    this._text_24 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_23,'label',new import3.InlineArray2(2,'for','lastName'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Last Name:',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._vc_28 = new import14.ViewContainer(28,23,this,this._anchor_28);
    this._TemplateRef_28_5 = new import21.TemplateRef_(this,28,this._anchor_28);
    this._NgIf_28_6 = new import15.Wrapper_NgIf(this._vc_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_23,'input',new import3.InlineArray16(10,'class','form-control','formControlName','lastName','id','lastName','placeholder','Last Name...','type','text'),(null as any));
    this._DefaultValueAccessor_30_3 = new import16.Wrapper_DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_30));
    this._NG_VALUE_ACCESSOR_30_4 = [this._DefaultValueAccessor_30_3.context];
    this._FormControlName_30_5 = new import17.Wrapper_FormControlName(this._ControlContainer_9_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_30_4);
    this._NgControl_30_6 = this._FormControlName_30_5.context;
    this._NgControlStatus_30_7 = new import12.Wrapper_NgControlStatus(this._NgControl_30_6);
    this._text_31 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._text_32 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_9,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'Save',(null as any));
    this._text_35 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_9,'button',new import3.InlineArray4(4,'class','btn btn-default','type','button'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Cancel',(null as any));
    this._text_38 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_9,'button',new import3.InlineArray8(6,'class','btn btn-warning','style','float:right','type','button'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Logout',(null as any));
    this._text_41 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_43 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_9));
    this._FormGroupDirective_9_3.subscribe(this,this.eventHandler(this.handleEvent_9),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_20));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_30));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_36,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_36));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_39));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import22.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import21.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import22.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import23.DefaultValueAccessor) && (20 === requestNodeIndex))) { return this._DefaultValueAccessor_20_3.context; }
    if (((token === import24.NG_VALUE_ACCESSOR) && (20 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_20_4; }
    if (((token === import25.FormControlName) && (20 === requestNodeIndex))) { return this._FormControlName_20_5.context; }
    if (((token === import26.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_6; }
    if (((token === import27.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_7.context; }
    if (((token === import28.NgClass) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._NgClass_11_3.context; }
    if (((token === import21.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import22.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    if (((token === import23.DefaultValueAccessor) && (30 === requestNodeIndex))) { return this._DefaultValueAccessor_30_3.context; }
    if (((token === import24.NG_VALUE_ACCESSOR) && (30 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_30_4; }
    if (((token === import25.FormControlName) && (30 === requestNodeIndex))) { return this._FormControlName_30_5.context; }
    if (((token === import26.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_6; }
    if (((token === import27.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_7.context; }
    if (((token === import28.NgClass) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgClass_23_3.context; }
    if (((token === import29.FormGroupDirective) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._FormGroupDirective_9_3.context; }
    if (((token === import30.ControlContainer) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ControlContainer_9_4; }
    if (((token === import27.NgControlStatusGroup) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgControlStatusGroup_9_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_9_0_0:any = this.context.profileForm;
    this._FormGroupDirective_9_3.check_form(currVal_9_0_0,throwOnChange,false);
    this._FormGroupDirective_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgControlStatusGroup_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_11_0_0:any = 'form-group';
    this._NgClass_11_3.check_klass(currVal_11_0_0,throwOnChange,false);
    const currVal_11_0_1:any = this._map_68(!this.context.validateFirstName());
    this._NgClass_11_3.check_ngClass(currVal_11_0_1,throwOnChange,false);
    this._NgClass_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_16_0_0:boolean = (!this.context.validateFirstName() && this.context.profileForm.get('firstName').hasError('required'));
    this._NgIf_16_6.check_ngIf(currVal_16_0_0,throwOnChange,false);
    this._NgIf_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    const currVal_18_0_0:boolean = (!this.context.validateFirstName() && this.context.profileForm.get('firstName').hasError('pattern'));
    this._NgIf_18_6.check_ngIf(currVal_18_0_0,throwOnChange,false);
    this._NgIf_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    this._DefaultValueAccessor_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_20_1_0:any = 'firstName';
    this._FormControlName_20_5.check_name(currVal_20_1_0,throwOnChange,false);
    this._FormControlName_20_5.ngDoCheck(this,this._el_20,throwOnChange);
    this._NgControlStatus_20_7.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_23_0_0:any = 'form-group';
    this._NgClass_23_3.check_klass(currVal_23_0_0,throwOnChange,false);
    const currVal_23_0_1:any = this._map_69(!this.context.validateLastName());
    this._NgClass_23_3.check_ngClass(currVal_23_0_1,throwOnChange,false);
    this._NgClass_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_28_0_0:boolean = !this.context.validateLastName();
    this._NgIf_28_6.check_ngIf(currVal_28_0_0,throwOnChange,false);
    this._NgIf_28_6.ngDoCheck(this,this._anchor_28,throwOnChange);
    this._DefaultValueAccessor_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    const currVal_30_1_0:any = 'lastName';
    this._FormControlName_30_5.check_name(currVal_30_1_0,throwOnChange,false);
    this._FormControlName_30_5.ngDoCheck(this,this._el_30,throwOnChange);
    this._NgControlStatus_30_7.ngDoCheck(this,this._el_30,throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_28.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_9_5.checkHost(this,this,this._el_9,throwOnChange);
    this._NgControlStatus_20_7.checkHost(this,this,this._el_20,throwOnChange);
    this._NgControlStatus_30_7.checkHost(this,this,this._el_30,throwOnChange);
  }
  destroyInternal():void {
    this._vc_16.destroyNestedViews();
    this._vc_18.destroyNestedViews();
    this._vc_28.destroyNestedViews();
    this._FormControlName_20_5.ngOnDestroy();
    this._FormControlName_30_5.ngOnDestroy();
    this._FormGroupDirective_9_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 16)) { return new View_ProfileComponent1(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 18)) { return new View_ProfileComponent2(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    if ((nodeIndex == 28)) { return new View_ProfileComponent3(this.viewUtils,this,28,this._anchor_28,this._vc_28); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_9_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.saveProfile(this.context.profileForm.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_20_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_30_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_36(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.cancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.logout()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ProfileComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_ProfileComponent1,renderType_ProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ProfileComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_ProfileComponent2,renderType_ProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Must start with a letter',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ProfileComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_ProfileComponent3,renderType_ProfileComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}