/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/events/create-event.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../app/events/shared/event.service';
import * as import10 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import18 from '../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory';
import * as import19 from './location-validator.directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_model_group.ngfactory';
import * as import21 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import22 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/common/src/directives/ng_if';
import * as import26 from '@angular/forms/src/directives/default_value_accessor';
import * as import27 from '@angular/forms/src/directives/validators';
import * as import28 from '@angular/forms/src/validators';
import * as import29 from '@angular/forms/src/directives/control_value_accessor';
import * as import30 from '@angular/forms/src/directives/ng_model';
import * as import31 from '@angular/forms/src/directives/ng_control';
import * as import32 from '@angular/forms/src/directives/ng_control_status';
import * as import33 from '@angular/common/src/directives/ng_class';
import * as import34 from '@angular/forms/src/directives/number_value_accessor';
import * as import35 from '../../../app/events/location-validator.directive';
import * as import36 from '@angular/forms/src/directives/ng_model_group';
import * as import37 from '@angular/forms/src/directives/control_container';
import * as import38 from '@angular/forms/src/directives/ng_form';
import * as import39 from '@angular/core/src/security';
export class Wrapper_CreateEventComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CreateEventComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.CreateEventComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_CreateEventComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CreateEventComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CreateEventComponent>;
  _CreateEventComponent_0_3:Wrapper_CreateEventComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreateEventComponent_Host0,renderType_CreateEventComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CreateEventComponent0(this.viewUtils,this,0,this._el_0);
    this._CreateEventComponent_0_3 = new Wrapper_CreateEventComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.EventService,this.parentIndex));
    this.compView_0.create(this._CreateEventComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CreateEventComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CreateEventComponent) && (0 === requestNodeIndex))) { return this._CreateEventComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CreateEventComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CreateEventComponentNgFactory:import7.ComponentFactory<import0.CreateEventComponent> = new import7.ComponentFactory<import0.CreateEventComponent>('ng-component',View_CreateEventComponent_Host0,import0.CreateEventComponent);
const styles_CreateEventComponent:any[] = ['em[_ngcontent-%COMP%] {float:right; color:#E05C65; padding-left:10px;}\n    .error[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {background-color:#E3C3C5;}\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-webkit-input-placeholder { color: #999; } \n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:-moz-placeholder { color: #999; }\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-moz-placeholder { color: #999; }\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:ms-input-placeholder  { color: #999; }'];
var renderType_CreateEventComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CreateEventComponent,{});
export class View_CreateEventComponent0 extends import1.AppView<import0.CreateEventComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import10.Wrapper_NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import11.Wrapper_NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _NgClass_9_3:import12.Wrapper_NgClass;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import13.ViewContainer;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import14.Wrapper_NgIf;
  _text_15:any;
  _el_16:any;
  _DefaultValueAccessor_16_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_16_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_16_5:any[];
  _NG_VALUE_ACCESSOR_16_6:any[];
  _NgModel_16_7:import17.Wrapper_NgModel;
  _NgControl_16_8:any;
  _NgControlStatus_16_9:import11.Wrapper_NgControlStatus;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _NgClass_19_3:import12.Wrapper_NgClass;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _vc_24:import13.ViewContainer;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import14.Wrapper_NgIf;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_26_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_26_5:any[];
  _NG_VALUE_ACCESSOR_26_6:any[];
  _NgModel_26_7:import17.Wrapper_NgModel;
  _NgControl_26_8:any;
  _NgControlStatus_26_9:import11.Wrapper_NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _NgClass_29_3:import12.Wrapper_NgClass;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _vc_34:import13.ViewContainer;
  _TemplateRef_34_5:any;
  _NgIf_34_6:import14.Wrapper_NgIf;
  _text_35:any;
  _el_36:any;
  _DefaultValueAccessor_36_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_36_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_36_5:any[];
  _NG_VALUE_ACCESSOR_36_6:any[];
  _NgModel_36_7:import17.Wrapper_NgModel;
  _NgControl_36_8:any;
  _NgControlStatus_36_9:import11.Wrapper_NgControlStatus;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _NgClass_39_3:import12.Wrapper_NgClass;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _anchor_44:any;
  /*private*/ _vc_44:import13.ViewContainer;
  _TemplateRef_44_5:any;
  _NgIf_44_6:import14.Wrapper_NgIf;
  _text_45:any;
  _el_46:any;
  _DefaultValueAccessor_46_3:import15.Wrapper_DefaultValueAccessor;
  _NumberValueAccessor_46_4:import18.Wrapper_NumberValueAccessor;
  _RequiredValidator_46_5:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_46_6:any[];
  _NG_VALUE_ACCESSOR_46_7:any[];
  _NgModel_46_8:import17.Wrapper_NgModel;
  _NgControl_46_9:any;
  _NgControlStatus_46_10:import11.Wrapper_NgControlStatus;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _LocationValidator_49_3:import19.Wrapper_LocationValidator;
  _NG_VALIDATORS_49_4:any[];
  _NgModelGroup_49_5:import20.Wrapper_NgModelGroup;
  _ControlContainer_49_6:any;
  _NgControlStatusGroup_49_7:import11.Wrapper_NgControlStatusGroup;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _anchor_56:any;
  /*private*/ _vc_56:import13.ViewContainer;
  _TemplateRef_56_5:any;
  _NgIf_56_6:import14.Wrapper_NgIf;
  _text_57:any;
  _el_58:any;
  _DefaultValueAccessor_58_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_58_4:any[];
  _NgModel_58_5:import17.Wrapper_NgModel;
  _NgControl_58_6:any;
  _NgControlStatus_58_7:import11.Wrapper_NgControlStatus;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _DefaultValueAccessor_65_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_65_4:any[];
  _NgModel_65_5:import17.Wrapper_NgModel;
  _NgControl_65_6:any;
  _NgControlStatus_65_7:import11.Wrapper_NgControlStatus;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _DefaultValueAccessor_70_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_70_4:any[];
  _NgModel_70_5:import17.Wrapper_NgModel;
  _NgControl_70_6:any;
  _NgControlStatus_70_7:import11.Wrapper_NgControlStatus;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _DefaultValueAccessor_80_3:import15.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_80_4:any[];
  _NgModel_80_5:import17.Wrapper_NgModel;
  _NgControl_80_6:any;
  _NgControlStatus_80_7:import11.Wrapper_NgControlStatus;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _NgClass_83_3:import12.Wrapper_NgClass;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _anchor_88:any;
  /*private*/ _vc_88:import13.ViewContainer;
  _TemplateRef_88_5:any;
  _NgIf_88_6:import14.Wrapper_NgIf;
  _text_89:any;
  _el_90:any;
  _DefaultValueAccessor_90_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_90_4:import16.Wrapper_RequiredValidator;
  _PatternValidator_90_5:import16.Wrapper_PatternValidator;
  _NG_VALIDATORS_90_6:any[];
  _NG_VALUE_ACCESSOR_90_7:any[];
  _NgModel_90_8:import17.Wrapper_NgModel;
  _NgControl_90_9:any;
  _NgControlStatus_90_10:import11.Wrapper_NgControlStatus;
  _text_91:any;
  _anchor_92:any;
  /*private*/ _vc_92:import13.ViewContainer;
  _TemplateRef_92_5:any;
  _NgIf_92_6:import14.Wrapper_NgIf;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _map_193:any;
  _map_194:any;
  _map_195:any;
  _map_196:any;
  _map_197:any;
  /*private*/ _expr_198:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreateEventComponent0,renderType_CreateEventComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_193 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_194 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_195 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_196 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_197 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._expr_198 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'h1',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'New Event',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'form',new import3.InlineArray4(4,'autocomplete','off','novalidate',''),(null as any));
    this._NgForm_7_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3.context;
    this._NgControlStatusGroup_7_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_9_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import22.KeyValueDiffers,this.parentIndex),new import23.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'label',new import3.InlineArray2(2,'for','eventName'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Event Name:',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_14 = new import13.ViewContainer(14,9,this,this._anchor_14);
    this._TemplateRef_14_5 = new import24.TemplateRef_(this,14,this._anchor_14);
    this._NgIf_14_6 = new import14.Wrapper_NgIf(this._vc_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_9,'input',new import3.InlineArray16(12,'class','form-control','id','name','name','name','placeholder','Name of your event...','required','','type','text'),(null as any));
    this._DefaultValueAccessor_16_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_16));
    this._RequiredValidator_16_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_16_5 = [this._RequiredValidator_16_4.context];
    this._NG_VALUE_ACCESSOR_16_6 = [this._DefaultValueAccessor_16_3.context];
    this._NgModel_16_7 = new import17.Wrapper_NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_16_5,(null as any),this._NG_VALUE_ACCESSOR_16_6);
    this._NgControl_16_8 = this._NgModel_16_7.context;
    this._NgControlStatus_16_9 = new import11.Wrapper_NgControlStatus(this._NgControl_16_8);
    this._text_17 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_19_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import22.KeyValueDiffers,this.parentIndex),new import23.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'label',new import3.InlineArray2(2,'for','eventDate'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Event Date:',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_24 = new import13.ViewContainer(24,19,this,this._anchor_24);
    this._TemplateRef_24_5 = new import24.TemplateRef_(this,24,this._anchor_24);
    this._NgIf_24_6 = new import14.Wrapper_NgIf(this._vc_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_19,'input',new import3.InlineArray16(12,'class','form-control','id','eventDate','name','date','placeholder','format (mm/dd/yyyy)...','required','','type','text'),(null as any));
    this._DefaultValueAccessor_26_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_26));
    this._RequiredValidator_26_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_26_5 = [this._RequiredValidator_26_4.context];
    this._NG_VALUE_ACCESSOR_26_6 = [this._DefaultValueAccessor_26_3.context];
    this._NgModel_26_7 = new import17.Wrapper_NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_26_5,(null as any),this._NG_VALUE_ACCESSOR_26_6);
    this._NgControl_26_8 = this._NgModel_26_7.context;
    this._NgControlStatus_26_9 = new import11.Wrapper_NgControlStatus(this._NgControl_26_8);
    this._text_27 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_29_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import22.KeyValueDiffers,this.parentIndex),new import23.ElementRef(this._el_29),this.renderer);
    this._text_30 = this.renderer.createText(this._el_29,'\n      ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'label',new import3.InlineArray2(2,'for','eventTime'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Event Time:',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n      ',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_29,(null as any));
    this._vc_34 = new import13.ViewContainer(34,29,this,this._anchor_34);
    this._TemplateRef_34_5 = new import24.TemplateRef_(this,34,this._anchor_34);
    this._NgIf_34_6 = new import14.Wrapper_NgIf(this._vc_34.vcRef,this._TemplateRef_34_5);
    this._text_35 = this.renderer.createText(this._el_29,'\n      ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_29,'input',new import3.InlineArray16(12,'class','form-control','id','eventTime','name','time','placeholder','start and end time...','required','','type','text'),(null as any));
    this._DefaultValueAccessor_36_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_36));
    this._RequiredValidator_36_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_36_5 = [this._RequiredValidator_36_4.context];
    this._NG_VALUE_ACCESSOR_36_6 = [this._DefaultValueAccessor_36_3.context];
    this._NgModel_36_7 = new import17.Wrapper_NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_36_5,(null as any),this._NG_VALUE_ACCESSOR_36_6);
    this._NgControl_36_8 = this._NgModel_36_7.context;
    this._NgControlStatus_36_9 = new import11.Wrapper_NgControlStatus(this._NgControl_36_8);
    this._text_37 = this.renderer.createText(this._el_29,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_39_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import22.KeyValueDiffers,this.parentIndex),new import23.ElementRef(this._el_39),this.renderer);
    this._text_40 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'label',new import3.InlineArray2(2,'for','eventPrice'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Event Price:',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._anchor_44 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._vc_44 = new import13.ViewContainer(44,39,this,this._anchor_44);
    this._TemplateRef_44_5 = new import24.TemplateRef_(this,44,this._anchor_44);
    this._NgIf_44_6 = new import14.Wrapper_NgIf(this._vc_44.vcRef,this._TemplateRef_44_5);
    this._text_45 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_39,'input',new import3.InlineArray16(12,'class','form-control','id','eventPrice','name','price','placeholder','event price...','required','','type','number'),(null as any));
    this._DefaultValueAccessor_46_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_46));
    this._NumberValueAccessor_46_4 = new import18.Wrapper_NumberValueAccessor(this.renderer,new import23.ElementRef(this._el_46));
    this._RequiredValidator_46_5 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_46_6 = [this._RequiredValidator_46_5.context];
    this._NG_VALUE_ACCESSOR_46_7 = [
      this._DefaultValueAccessor_46_3.context,
      this._NumberValueAccessor_46_4.context
    ]
    ;
    this._NgModel_46_8 = new import17.Wrapper_NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_46_6,(null as any),this._NG_VALUE_ACCESSOR_46_7);
    this._NgControl_46_9 = this._NgModel_46_8.context;
    this._NgControlStatus_46_10 = new import11.Wrapper_NgControlStatus(this._NgControl_46_9);
    this._text_47 = this.renderer.createText(this._el_39,'\n    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_7,'\n\n    ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray4(4,'ngModelGroup','location','validateLocation',''),(null as any));
    this._LocationValidator_49_3 = new import19.Wrapper_LocationValidator();
    this._NG_VALIDATORS_49_4 = [this._LocationValidator_49_3.context];
    this._NgModelGroup_49_5 = new import20.Wrapper_NgModelGroup(this._ControlContainer_7_4,this._NG_VALIDATORS_49_4,(null as any));
    this._ControlContainer_49_6 = this._NgModelGroup_49_5.context;
    this._NgControlStatusGroup_49_7 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_49_6);
    this._text_50 = this.renderer.createText(this._el_49,'\n      ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'label',new import3.InlineArray2(2,'for','address'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'Event Location:',(null as any));
    this._text_55 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._anchor_56 = this.renderer.createTemplateAnchor(this._el_51,(null as any));
    this._vc_56 = new import13.ViewContainer(56,51,this,this._anchor_56);
    this._TemplateRef_56_5 = new import24.TemplateRef_(this,56,this._anchor_56);
    this._NgIf_56_6 = new import14.Wrapper_NgIf(this._vc_56.vcRef,this._TemplateRef_56_5);
    this._text_57 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_51,'input',new import3.InlineArray16(10,'class','form-control','id','address','name','address','placeholder','Address of event...','type','text'),(null as any));
    this._DefaultValueAccessor_58_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_58));
    this._NG_VALUE_ACCESSOR_58_4 = [this._DefaultValueAccessor_58_3.context];
    this._NgModel_58_5 = new import17.Wrapper_NgModel(this._ControlContainer_49_6,(null as any),(null as any),this._NG_VALUE_ACCESSOR_58_4);
    this._NgControl_58_6 = this._NgModel_58_5.context;
    this._NgControlStatus_58_7 = new import11.Wrapper_NgControlStatus(this._NgControl_58_6);
    this._text_59 = this.renderer.createText(this._el_51,'\n      ',(null as any));
    this._text_60 = this.renderer.createText(this._el_49,'\n      ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_49,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n          ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'input',new import3.InlineArray16(10,'class','form-control','id','city','name','city','placeholder','City...','type','text'),(null as any));
    this._DefaultValueAccessor_65_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_65));
    this._NG_VALUE_ACCESSOR_65_4 = [this._DefaultValueAccessor_65_3.context];
    this._NgModel_65_5 = new import17.Wrapper_NgModel(this._ControlContainer_49_6,(null as any),(null as any),this._NG_VALUE_ACCESSOR_65_4);
    this._NgControl_65_6 = this._NgModel_65_5.context;
    this._NgControlStatus_65_7 = new import11.Wrapper_NgControlStatus(this._NgControl_65_6);
    this._text_66 = this.renderer.createText(this._el_63,'\n        ',(null as any));
    this._text_67 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_61,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'\n          ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_68,'input',new import3.InlineArray16(10,'class','form-control','id','country','name','country','placeholder','Country...','type','text'),(null as any));
    this._DefaultValueAccessor_70_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_70));
    this._NG_VALUE_ACCESSOR_70_4 = [this._DefaultValueAccessor_70_3.context];
    this._NgModel_70_5 = new import17.Wrapper_NgModel(this._ControlContainer_49_6,(null as any),(null as any),this._NG_VALUE_ACCESSOR_70_4);
    this._NgControl_70_6 = this._NgModel_70_5.context;
    this._NgControlStatus_70_7 = new import11.Wrapper_NgControlStatus(this._NgControl_70_6);
    this._text_71 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._text_72 = this.renderer.createText(this._el_61,'\n      ',(null as any));
    this._text_73 = this.renderer.createText(this._el_49,'\n    ',(null as any));
    this._text_74 = this.renderer.createText(this._el_7,'\n    \n    ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'\n      ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_75,'label',new import3.InlineArray2(2,'for','onlineUrl'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'Online Url:',(null as any));
    this._text_79 = this.renderer.createText(this._el_75,'\n      ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_75,'input',new import3.InlineArray16(10,'class','form-control','id','onlineUrl','name','onlineUrl','placeholder','Online Url...','type','text'),(null as any));
    this._DefaultValueAccessor_80_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_80));
    this._NG_VALUE_ACCESSOR_80_4 = [this._DefaultValueAccessor_80_3.context];
    this._NgModel_80_5 = new import17.Wrapper_NgModel(this._ControlContainer_7_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_80_4);
    this._NgControl_80_6 = this._NgModel_80_5.context;
    this._NgControlStatus_80_7 = new import11.Wrapper_NgControlStatus(this._NgControl_80_6);
    this._text_81 = this.renderer.createText(this._el_75,'\n    ',(null as any));
    this._text_82 = this.renderer.createText(this._el_7,'\n\n    ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_83_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import21.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import22.KeyValueDiffers,this.parentIndex),new import23.ElementRef(this._el_83),this.renderer);
    this._text_84 = this.renderer.createText(this._el_83,'\n      ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_83,'label',new import3.InlineArray2(2,'for','imageUrl'),(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'Image:',(null as any));
    this._text_87 = this.renderer.createText(this._el_83,'\n      ',(null as any));
    this._anchor_88 = this.renderer.createTemplateAnchor(this._el_83,(null as any));
    this._vc_88 = new import13.ViewContainer(88,83,this,this._anchor_88);
    this._TemplateRef_88_5 = new import24.TemplateRef_(this,88,this._anchor_88);
    this._NgIf_88_6 = new import14.Wrapper_NgIf(this._vc_88.vcRef,this._TemplateRef_88_5);
    this._text_89 = this.renderer.createText(this._el_83,'\n      ',(null as any));
    this._el_90 = import3.createRenderElement(this.renderer,this._el_83,'input',new import3.InlineArray16(14,'class','form-control','id','imageUrl','name','imageUrl','pattern','.*\\/.*.(png|jpg)','placeholder','url of image...','required','','type','text'),(null as any));
    this._DefaultValueAccessor_90_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_90));
    this._RequiredValidator_90_4 = new import16.Wrapper_RequiredValidator();
    this._PatternValidator_90_5 = new import16.Wrapper_PatternValidator();
    this._NG_VALIDATORS_90_6 = [
      this._RequiredValidator_90_4.context,
      this._PatternValidator_90_5.context
    ]
    ;
    this._NG_VALUE_ACCESSOR_90_7 = [this._DefaultValueAccessor_90_3.context];
    this._NgModel_90_8 = new import17.Wrapper_NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_90_6,(null as any),this._NG_VALUE_ACCESSOR_90_7);
    this._NgControl_90_9 = this._NgModel_90_8.context;
    this._NgControlStatus_90_10 = new import11.Wrapper_NgControlStatus(this._NgControl_90_9);
    this._text_91 = this.renderer.createText(this._el_83,'\n      ',(null as any));
    this._anchor_92 = this.renderer.createTemplateAnchor(this._el_83,(null as any));
    this._vc_92 = new import13.ViewContainer(92,83,this,this._anchor_92);
    this._TemplateRef_92_5 = new import24.TemplateRef_(this,92,this._anchor_92);
    this._NgIf_92_6 = new import14.Wrapper_NgIf(this._vc_92.vcRef,this._TemplateRef_92_5);
    this._text_93 = this.renderer.createText(this._el_83,'\n    ',(null as any));
    this._text_94 = this.renderer.createText(this._el_7,'\n\n    ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_7,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'Save',(null as any));
    this._text_97 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_98 = import3.createRenderElement(this.renderer,this._el_7,'button',new import3.InlineArray4(4,'class','btn btn-default','type','button'),(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'Cancel',(null as any));
    this._text_100 = this.renderer.createText(this._el_7,'\n\n  ',(null as any));
    this._text_101 = this.renderer.createText(this._el_5,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_7));
    this._NgForm_7_3.subscribe(this,this.eventHandler(this.handleEvent_7),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_16));
    this._NgModel_16_7.subscribe(this,this.eventHandler(this.handleEvent_16),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_26));
    this._NgModel_26_7.subscribe(this,this.eventHandler(this.handleEvent_26),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_36,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_36));
    this._NgModel_36_7.subscribe(this,this.eventHandler(this.handleEvent_36),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_46,new import3.InlineArray8(8,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any),'change',(null as any)),this.eventHandler(this.handleEvent_46));
    this._NgModel_46_8.subscribe(this,this.eventHandler(this.handleEvent_46),true);
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_58,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_58));
    this._NgModel_58_5.subscribe(this,this.eventHandler(this.handleEvent_58),true);
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_65,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_65));
    this._NgModel_65_5.subscribe(this,this.eventHandler(this.handleEvent_65),true);
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_70,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_70));
    this._NgModel_70_5.subscribe(this,this.eventHandler(this.handleEvent_70),true);
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_80,new import3.InlineArray8(8,'ngModelChange',(null as any),'change',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_80));
    this._NgModel_80_5.subscribe(this,this.eventHandler(this.handleEvent_80),true);
    var disposable_9:Function = import3.subscribeToRenderElement(this,this._el_90,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_90));
    this._NgModel_90_8.subscribe(this,this.eventHandler(this.handleEvent_90),true);
    var disposable_10:Function = import3.subscribeToRenderElement(this,this._el_98,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_98));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._anchor_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._anchor_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._anchor_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._anchor_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import25.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    if (((token === import26.DefaultValueAccessor) && (16 === requestNodeIndex))) { return this._DefaultValueAccessor_16_3.context; }
    if (((token === import27.RequiredValidator) && (16 === requestNodeIndex))) { return this._RequiredValidator_16_4.context; }
    if (((token === import28.NG_VALIDATORS) && (16 === requestNodeIndex))) { return this._NG_VALIDATORS_16_5; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_6; }
    if (((token === import30.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_7.context; }
    if (((token === import31.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_8; }
    if (((token === import32.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_9.context; }
    if (((token === import33.NgClass) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgClass_9_3.context; }
    if (((token === import24.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import25.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6.context; }
    if (((token === import26.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3.context; }
    if (((token === import27.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4.context; }
    if (((token === import28.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_5; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_6; }
    if (((token === import30.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_7.context; }
    if (((token === import31.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_8; }
    if (((token === import32.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_9.context; }
    if (((token === import33.NgClass) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgClass_19_3.context; }
    if (((token === import24.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import25.NgIf) && (34 === requestNodeIndex))) { return this._NgIf_34_6.context; }
    if (((token === import26.DefaultValueAccessor) && (36 === requestNodeIndex))) { return this._DefaultValueAccessor_36_3.context; }
    if (((token === import27.RequiredValidator) && (36 === requestNodeIndex))) { return this._RequiredValidator_36_4.context; }
    if (((token === import28.NG_VALIDATORS) && (36 === requestNodeIndex))) { return this._NG_VALIDATORS_36_5; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (36 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_36_6; }
    if (((token === import30.NgModel) && (36 === requestNodeIndex))) { return this._NgModel_36_7.context; }
    if (((token === import31.NgControl) && (36 === requestNodeIndex))) { return this._NgControl_36_8; }
    if (((token === import32.NgControlStatus) && (36 === requestNodeIndex))) { return this._NgControlStatus_36_9.context; }
    if (((token === import33.NgClass) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgClass_29_3.context; }
    if (((token === import24.TemplateRef) && (44 === requestNodeIndex))) { return this._TemplateRef_44_5; }
    if (((token === import25.NgIf) && (44 === requestNodeIndex))) { return this._NgIf_44_6.context; }
    if (((token === import26.DefaultValueAccessor) && (46 === requestNodeIndex))) { return this._DefaultValueAccessor_46_3.context; }
    if (((token === import34.NumberValueAccessor) && (46 === requestNodeIndex))) { return this._NumberValueAccessor_46_4.context; }
    if (((token === import27.RequiredValidator) && (46 === requestNodeIndex))) { return this._RequiredValidator_46_5.context; }
    if (((token === import28.NG_VALIDATORS) && (46 === requestNodeIndex))) { return this._NG_VALIDATORS_46_6; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (46 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_46_7; }
    if (((token === import30.NgModel) && (46 === requestNodeIndex))) { return this._NgModel_46_8.context; }
    if (((token === import31.NgControl) && (46 === requestNodeIndex))) { return this._NgControl_46_9; }
    if (((token === import32.NgControlStatus) && (46 === requestNodeIndex))) { return this._NgControlStatus_46_10.context; }
    if (((token === import33.NgClass) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._NgClass_39_3.context; }
    if (((token === import24.TemplateRef) && (56 === requestNodeIndex))) { return this._TemplateRef_56_5; }
    if (((token === import25.NgIf) && (56 === requestNodeIndex))) { return this._NgIf_56_6.context; }
    if (((token === import26.DefaultValueAccessor) && (58 === requestNodeIndex))) { return this._DefaultValueAccessor_58_3.context; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (58 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_58_4; }
    if (((token === import30.NgModel) && (58 === requestNodeIndex))) { return this._NgModel_58_5.context; }
    if (((token === import31.NgControl) && (58 === requestNodeIndex))) { return this._NgControl_58_6; }
    if (((token === import32.NgControlStatus) && (58 === requestNodeIndex))) { return this._NgControlStatus_58_7.context; }
    if (((token === import26.DefaultValueAccessor) && (65 === requestNodeIndex))) { return this._DefaultValueAccessor_65_3.context; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (65 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_65_4; }
    if (((token === import30.NgModel) && (65 === requestNodeIndex))) { return this._NgModel_65_5.context; }
    if (((token === import31.NgControl) && (65 === requestNodeIndex))) { return this._NgControl_65_6; }
    if (((token === import32.NgControlStatus) && (65 === requestNodeIndex))) { return this._NgControlStatus_65_7.context; }
    if (((token === import26.DefaultValueAccessor) && (70 === requestNodeIndex))) { return this._DefaultValueAccessor_70_3.context; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (70 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_70_4; }
    if (((token === import30.NgModel) && (70 === requestNodeIndex))) { return this._NgModel_70_5.context; }
    if (((token === import31.NgControl) && (70 === requestNodeIndex))) { return this._NgControl_70_6; }
    if (((token === import32.NgControlStatus) && (70 === requestNodeIndex))) { return this._NgControlStatus_70_7.context; }
    if (((token === import35.LocationValidator) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._LocationValidator_49_3.context; }
    if (((token === import28.NG_VALIDATORS) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._NG_VALIDATORS_49_4; }
    if (((token === import36.NgModelGroup) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._NgModelGroup_49_5.context; }
    if (((token === import37.ControlContainer) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._ControlContainer_49_6; }
    if (((token === import32.NgControlStatusGroup) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._NgControlStatusGroup_49_7.context; }
    if (((token === import26.DefaultValueAccessor) && (80 === requestNodeIndex))) { return this._DefaultValueAccessor_80_3.context; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (80 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_80_4; }
    if (((token === import30.NgModel) && (80 === requestNodeIndex))) { return this._NgModel_80_5.context; }
    if (((token === import31.NgControl) && (80 === requestNodeIndex))) { return this._NgControl_80_6; }
    if (((token === import32.NgControlStatus) && (80 === requestNodeIndex))) { return this._NgControlStatus_80_7.context; }
    if (((token === import24.TemplateRef) && (88 === requestNodeIndex))) { return this._TemplateRef_88_5; }
    if (((token === import25.NgIf) && (88 === requestNodeIndex))) { return this._NgIf_88_6.context; }
    if (((token === import26.DefaultValueAccessor) && (90 === requestNodeIndex))) { return this._DefaultValueAccessor_90_3.context; }
    if (((token === import27.RequiredValidator) && (90 === requestNodeIndex))) { return this._RequiredValidator_90_4.context; }
    if (((token === import27.PatternValidator) && (90 === requestNodeIndex))) { return this._PatternValidator_90_5.context; }
    if (((token === import28.NG_VALIDATORS) && (90 === requestNodeIndex))) { return this._NG_VALIDATORS_90_6; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (90 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_90_7; }
    if (((token === import30.NgModel) && (90 === requestNodeIndex))) { return this._NgModel_90_8.context; }
    if (((token === import31.NgControl) && (90 === requestNodeIndex))) { return this._NgControl_90_9; }
    if (((token === import32.NgControlStatus) && (90 === requestNodeIndex))) { return this._NgControlStatus_90_10.context; }
    if (((token === import24.TemplateRef) && (92 === requestNodeIndex))) { return this._TemplateRef_92_5; }
    if (((token === import25.NgIf) && (92 === requestNodeIndex))) { return this._NgIf_92_6.context; }
    if (((token === import33.NgClass) && ((83 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._NgClass_83_3.context; }
    if (((token === import38.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._NgForm_7_3.context; }
    if (((token === import37.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._ControlContainer_7_4; }
    if (((token === import32.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._NgControlStatusGroup_7_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._NgControlStatusGroup_7_5.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_9_0_0:any = 'form-group';
    this._NgClass_9_3.check_klass(currVal_9_0_0,throwOnChange,false);
    var tmp_9_0_1_0:any = (null as any);
    const currVal_9_0_1:any = this._map_193(((((tmp_9_0_1_0 = this._NgForm_7_3.context.form.get('name')) == null)? (null as any): tmp_9_0_1_0.invalid) && (((tmp_9_0_1_0 = this._NgForm_7_3.context.form.get('name')) == null)? (null as any): tmp_9_0_1_0.touched)));
    this._NgClass_9_3.check_ngClass(currVal_9_0_1,throwOnChange,false);
    this._NgClass_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    var tmp_14_0_0_0:any = (null as any);
    const currVal_14_0_0:any = ((((tmp_14_0_0_0 = this._NgForm_7_3.context.form.get('name')) == null)? (null as any): tmp_14_0_0_0.invalid) && (((tmp_14_0_0_0 = this._NgForm_7_3.context.form.get('name')) == null)? (null as any): tmp_14_0_0_0.touched));
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    this._DefaultValueAccessor_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_16_1_0:any = '';
    this._RequiredValidator_16_4.check_required(currVal_16_1_0,throwOnChange,false);
    this._RequiredValidator_16_4.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_16_2_0:any = 'name';
    this._NgModel_16_7.check_name(currVal_16_2_0,throwOnChange,false);
    const currVal_16_2_1:any = this.context.event.name;
    this._NgModel_16_7.check_model(currVal_16_2_1,throwOnChange,false);
    this._NgModel_16_7.ngDoCheck(this,this._el_16,throwOnChange);
    this._NgControlStatus_16_9.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_19_0_0:any = 'form-group';
    this._NgClass_19_3.check_klass(currVal_19_0_0,throwOnChange,false);
    var tmp_19_0_1_0:any = (null as any);
    const currVal_19_0_1:any = this._map_194(((((tmp_19_0_1_0 = this._NgForm_7_3.context.form.get('date')) == null)? (null as any): tmp_19_0_1_0.invalid) && (((tmp_19_0_1_0 = this._NgForm_7_3.context.form.get('date')) == null)? (null as any): tmp_19_0_1_0.touched)));
    this._NgClass_19_3.check_ngClass(currVal_19_0_1,throwOnChange,false);
    this._NgClass_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    var tmp_24_0_0_0:any = (null as any);
    const currVal_24_0_0:any = ((((tmp_24_0_0_0 = this._NgForm_7_3.context.form.get('date')) == null)? (null as any): tmp_24_0_0_0.invalid) && (((tmp_24_0_0_0 = this._NgForm_7_3.context.form.get('date')) == null)? (null as any): tmp_24_0_0_0.touched));
    this._NgIf_24_6.check_ngIf(currVal_24_0_0,throwOnChange,false);
    this._NgIf_24_6.ngDoCheck(this,this._anchor_24,throwOnChange);
    this._DefaultValueAccessor_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_26_1_0:any = '';
    this._RequiredValidator_26_4.check_required(currVal_26_1_0,throwOnChange,false);
    this._RequiredValidator_26_4.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_26_2_0:any = 'date';
    this._NgModel_26_7.check_name(currVal_26_2_0,throwOnChange,false);
    const currVal_26_2_1:any = this.context.event.date;
    this._NgModel_26_7.check_model(currVal_26_2_1,throwOnChange,false);
    this._NgModel_26_7.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_9.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_29_0_0:any = 'form-group';
    this._NgClass_29_3.check_klass(currVal_29_0_0,throwOnChange,false);
    var tmp_29_0_1_0:any = (null as any);
    const currVal_29_0_1:any = this._map_195(((((tmp_29_0_1_0 = this._NgForm_7_3.context.form.get('time')) == null)? (null as any): tmp_29_0_1_0.invalid) && (((tmp_29_0_1_0 = this._NgForm_7_3.context.form.get('time')) == null)? (null as any): tmp_29_0_1_0.touched)));
    this._NgClass_29_3.check_ngClass(currVal_29_0_1,throwOnChange,false);
    this._NgClass_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    var tmp_34_0_0_0:any = (null as any);
    const currVal_34_0_0:any = ((((tmp_34_0_0_0 = this._NgForm_7_3.context.form.get('time')) == null)? (null as any): tmp_34_0_0_0.invalid) && (((tmp_34_0_0_0 = this._NgForm_7_3.context.form.get('time')) == null)? (null as any): tmp_34_0_0_0.touched));
    this._NgIf_34_6.check_ngIf(currVal_34_0_0,throwOnChange,false);
    this._NgIf_34_6.ngDoCheck(this,this._anchor_34,throwOnChange);
    this._DefaultValueAccessor_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    const currVal_36_1_0:any = '';
    this._RequiredValidator_36_4.check_required(currVal_36_1_0,throwOnChange,false);
    this._RequiredValidator_36_4.ngDoCheck(this,this._el_36,throwOnChange);
    const currVal_36_2_0:any = 'time';
    this._NgModel_36_7.check_name(currVal_36_2_0,throwOnChange,false);
    const currVal_36_2_1:any = this.context.event.time;
    this._NgModel_36_7.check_model(currVal_36_2_1,throwOnChange,false);
    this._NgModel_36_7.ngDoCheck(this,this._el_36,throwOnChange);
    this._NgControlStatus_36_9.ngDoCheck(this,this._el_36,throwOnChange);
    const currVal_39_0_0:any = 'form-group';
    this._NgClass_39_3.check_klass(currVal_39_0_0,throwOnChange,false);
    var tmp_39_0_1_0:any = (null as any);
    const currVal_39_0_1:any = this._map_196(((((tmp_39_0_1_0 = this._NgForm_7_3.context.form.get('price')) == null)? (null as any): tmp_39_0_1_0.invalid) && (((tmp_39_0_1_0 = this._NgForm_7_3.context.form.get('price')) == null)? (null as any): tmp_39_0_1_0.touched)));
    this._NgClass_39_3.check_ngClass(currVal_39_0_1,throwOnChange,false);
    this._NgClass_39_3.ngDoCheck(this,this._el_39,throwOnChange);
    var tmp_44_0_0_0:any = (null as any);
    const currVal_44_0_0:any = ((((tmp_44_0_0_0 = this._NgForm_7_3.context.form.get('price')) == null)? (null as any): tmp_44_0_0_0.invalid) && (((tmp_44_0_0_0 = this._NgForm_7_3.context.form.get('price')) == null)? (null as any): tmp_44_0_0_0.touched));
    this._NgIf_44_6.check_ngIf(currVal_44_0_0,throwOnChange,false);
    this._NgIf_44_6.ngDoCheck(this,this._anchor_44,throwOnChange);
    this._DefaultValueAccessor_46_3.ngDoCheck(this,this._el_46,throwOnChange);
    this._NumberValueAccessor_46_4.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_46_2_0:any = '';
    this._RequiredValidator_46_5.check_required(currVal_46_2_0,throwOnChange,false);
    this._RequiredValidator_46_5.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_46_3_0:any = 'price';
    this._NgModel_46_8.check_name(currVal_46_3_0,throwOnChange,false);
    const currVal_46_3_1:any = this.context.event.price;
    this._NgModel_46_8.check_model(currVal_46_3_1,throwOnChange,false);
    this._NgModel_46_8.ngDoCheck(this,this._el_46,throwOnChange);
    this._NgControlStatus_46_10.ngDoCheck(this,this._el_46,throwOnChange);
    this._LocationValidator_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_1_0:any = 'location';
    this._NgModelGroup_49_5.check_name(currVal_49_1_0,throwOnChange,false);
    this._NgModelGroup_49_5.ngDoCheck(this,this._el_49,throwOnChange);
    this._NgControlStatusGroup_49_7.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_56_0_0:any = (((this._NgModelGroup_49_5.context == null)? (null as any): this._NgModelGroup_49_5.context.invalid) && ((this._NgModelGroup_49_5.context == null)? (null as any): this._NgModelGroup_49_5.context.touched));
    this._NgIf_56_6.check_ngIf(currVal_56_0_0,throwOnChange,false);
    this._NgIf_56_6.ngDoCheck(this,this._anchor_56,throwOnChange);
    this._DefaultValueAccessor_58_3.ngDoCheck(this,this._el_58,throwOnChange);
    const currVal_58_1_0:any = 'address';
    this._NgModel_58_5.check_name(currVal_58_1_0,throwOnChange,false);
    const currVal_58_1_1:any = this.context.event.location.address;
    this._NgModel_58_5.check_model(currVal_58_1_1,throwOnChange,false);
    this._NgModel_58_5.ngDoCheck(this,this._el_58,throwOnChange);
    this._NgControlStatus_58_7.ngDoCheck(this,this._el_58,throwOnChange);
    this._DefaultValueAccessor_65_3.ngDoCheck(this,this._el_65,throwOnChange);
    const currVal_65_1_0:any = 'city';
    this._NgModel_65_5.check_name(currVal_65_1_0,throwOnChange,false);
    const currVal_65_1_1:any = this.context.event.location.city;
    this._NgModel_65_5.check_model(currVal_65_1_1,throwOnChange,false);
    this._NgModel_65_5.ngDoCheck(this,this._el_65,throwOnChange);
    this._NgControlStatus_65_7.ngDoCheck(this,this._el_65,throwOnChange);
    this._DefaultValueAccessor_70_3.ngDoCheck(this,this._el_70,throwOnChange);
    const currVal_70_1_0:any = 'country';
    this._NgModel_70_5.check_name(currVal_70_1_0,throwOnChange,false);
    const currVal_70_1_1:any = this.context.event.location.country;
    this._NgModel_70_5.check_model(currVal_70_1_1,throwOnChange,false);
    this._NgModel_70_5.ngDoCheck(this,this._el_70,throwOnChange);
    this._NgControlStatus_70_7.ngDoCheck(this,this._el_70,throwOnChange);
    this._DefaultValueAccessor_80_3.ngDoCheck(this,this._el_80,throwOnChange);
    const currVal_80_1_0:any = 'onlineUrl';
    this._NgModel_80_5.check_name(currVal_80_1_0,throwOnChange,false);
    const currVal_80_1_1:any = this.context.event.onlineUrl;
    this._NgModel_80_5.check_model(currVal_80_1_1,throwOnChange,false);
    this._NgModel_80_5.ngDoCheck(this,this._el_80,throwOnChange);
    this._NgControlStatus_80_7.ngDoCheck(this,this._el_80,throwOnChange);
    const currVal_83_0_0:any = 'form-group';
    this._NgClass_83_3.check_klass(currVal_83_0_0,throwOnChange,false);
    var tmp_83_0_1_0:any = (null as any);
    const currVal_83_0_1:any = this._map_197(((((tmp_83_0_1_0 = this._NgForm_7_3.context.form.get('imageUrl')) == null)? (null as any): tmp_83_0_1_0.invalid) && (((tmp_83_0_1_0 = this._NgForm_7_3.context.form.get('imageUrl')) == null)? (null as any): tmp_83_0_1_0.touched)));
    this._NgClass_83_3.check_ngClass(currVal_83_0_1,throwOnChange,false);
    this._NgClass_83_3.ngDoCheck(this,this._el_83,throwOnChange);
    var tmp_88_0_0_0:any = (null as any);
    const currVal_88_0_0:any = ((((tmp_88_0_0_0 = this._NgForm_7_3.context.form.get('imageUrl')) == null)? (null as any): tmp_88_0_0_0.invalid) && (((tmp_88_0_0_0 = this._NgForm_7_3.context.form.get('imageUrl')) == null)? (null as any): tmp_88_0_0_0.touched));
    this._NgIf_88_6.check_ngIf(currVal_88_0_0,throwOnChange,false);
    this._NgIf_88_6.ngDoCheck(this,this._anchor_88,throwOnChange);
    this._DefaultValueAccessor_90_3.ngDoCheck(this,this._el_90,throwOnChange);
    const currVal_90_1_0:any = '';
    this._RequiredValidator_90_4.check_required(currVal_90_1_0,throwOnChange,false);
    this._RequiredValidator_90_4.ngDoCheck(this,this._el_90,throwOnChange);
    const currVal_90_2_0:any = '.*\\/.*.(png|jpg)';
    this._PatternValidator_90_5.check_pattern(currVal_90_2_0,throwOnChange,false);
    this._PatternValidator_90_5.ngDoCheck(this,this._el_90,throwOnChange);
    const currVal_90_3_0:any = 'imageUrl';
    this._NgModel_90_8.check_name(currVal_90_3_0,throwOnChange,false);
    const currVal_90_3_1:any = this.context.event.imageUrl;
    this._NgModel_90_8.check_model(currVal_90_3_1,throwOnChange,false);
    this._NgModel_90_8.ngDoCheck(this,this._el_90,throwOnChange);
    this._NgControlStatus_90_10.ngDoCheck(this,this._el_90,throwOnChange);
    var tmp_92_0_0_0:any = (null as any);
    const currVal_92_0_0:any = (((tmp_92_0_0_0 = this._NgForm_7_3.context.form.get('imageUrl')) == null)? (null as any): tmp_92_0_0_0.valid);
    this._NgIf_92_6.check_ngIf(currVal_92_0_0,throwOnChange,false);
    this._NgIf_92_6.ngDoCheck(this,this._anchor_92,throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_24.detectChangesInNestedViews(throwOnChange);
    this._vc_34.detectChangesInNestedViews(throwOnChange);
    this._vc_44.detectChangesInNestedViews(throwOnChange);
    this._vc_56.detectChangesInNestedViews(throwOnChange);
    this._vc_88.detectChangesInNestedViews(throwOnChange);
    this._vc_92.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_7_5.checkHost(this,this,this._el_7,throwOnChange);
    this._RequiredValidator_16_4.checkHost(this,this,this._el_16,throwOnChange);
    this._NgControlStatus_16_9.checkHost(this,this,this._el_16,throwOnChange);
    this._RequiredValidator_26_4.checkHost(this,this,this._el_26,throwOnChange);
    this._NgControlStatus_26_9.checkHost(this,this,this._el_26,throwOnChange);
    this._RequiredValidator_36_4.checkHost(this,this,this._el_36,throwOnChange);
    this._NgControlStatus_36_9.checkHost(this,this,this._el_36,throwOnChange);
    this._RequiredValidator_46_5.checkHost(this,this,this._el_46,throwOnChange);
    this._NgControlStatus_46_10.checkHost(this,this,this._el_46,throwOnChange);
    this._NgControlStatusGroup_49_7.checkHost(this,this,this._el_49,throwOnChange);
    this._NgControlStatus_58_7.checkHost(this,this,this._el_58,throwOnChange);
    this._NgControlStatus_65_7.checkHost(this,this,this._el_65,throwOnChange);
    this._NgControlStatus_70_7.checkHost(this,this,this._el_70,throwOnChange);
    this._NgControlStatus_80_7.checkHost(this,this,this._el_80,throwOnChange);
    this._RequiredValidator_90_4.checkHost(this,this,this._el_90,throwOnChange);
    this._PatternValidator_90_5.checkHost(this,this,this._el_90,throwOnChange);
    this._NgControlStatus_90_10.checkHost(this,this,this._el_90,throwOnChange);
    const currVal_198:any = this._NgForm_7_3.context.invalid;
    if (import3.checkBinding(throwOnChange,this._expr_198,currVal_198)) {
      this.renderer.setElementProperty(this._el_95,'disabled',currVal_198);
      this._expr_198 = currVal_198;
    }
  }
  destroyInternal():void {
    this._vc_14.destroyNestedViews();
    this._vc_24.destroyNestedViews();
    this._vc_34.destroyNestedViews();
    this._vc_44.destroyNestedViews();
    this._vc_56.destroyNestedViews();
    this._vc_88.destroyNestedViews();
    this._vc_92.destroyNestedViews();
    this._NgModel_16_7.ngOnDestroy();
    this._NgModel_26_7.ngOnDestroy();
    this._NgModel_36_7.ngOnDestroy();
    this._NgModel_46_8.ngOnDestroy();
    this._NgModel_58_5.ngOnDestroy();
    this._NgModel_65_5.ngOnDestroy();
    this._NgModel_70_5.ngOnDestroy();
    this._NgModel_80_5.ngOnDestroy();
    this._NgModel_90_8.ngOnDestroy();
    this._NgForm_7_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 14)) { return new View_CreateEventComponent1(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 24)) { return new View_CreateEventComponent2(this.viewUtils,this,24,this._anchor_24,this._vc_24); }
    if ((nodeIndex == 34)) { return new View_CreateEventComponent3(this.viewUtils,this,34,this._anchor_34,this._vc_34); }
    if ((nodeIndex == 44)) { return new View_CreateEventComponent4(this.viewUtils,this,44,this._anchor_44,this._vc_44); }
    if ((nodeIndex == 56)) { return new View_CreateEventComponent5(this.viewUtils,this,56,this._anchor_56,this._vc_56); }
    if ((nodeIndex == 88)) { return new View_CreateEventComponent6(this.viewUtils,this,88,this._anchor_88,this._vc_88); }
    if ((nodeIndex == 92)) { return new View_CreateEventComponent7(this.viewUtils,this,92,this._anchor_92,this._vc_92); }
    return (null as any);
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_7_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.saveEvent(this._NgForm_7_3.context.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_16_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_26_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.date = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_36(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_36_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.time = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_46(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_46_3.handleEvent(eventName,$event) && result);
    result = (this._NumberValueAccessor_46_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.price = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_58(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_58_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.location.address = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_65(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_65_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.location.city = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_70(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_70_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.location.country = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_80(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_80_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.onlineUrl = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'change')) {
      const pd_sub_1:any = ((<any>this._NgModelGroup_49_5.context.control.controls['address'].updateValueAndValidity()) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_90(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_90_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.event.imageUrl = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_98(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.cancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_CreateEventComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_CreateEventComponent1,renderType_CreateEventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateEventComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_CreateEventComponent2,renderType_CreateEventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateEventComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_CreateEventComponent3,renderType_CreateEventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateEventComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_CreateEventComponent4,renderType_CreateEventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateEventComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_CreateEventComponent5,renderType_CreateEventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'You must enter either the full location OR an online Url',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateEventComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_CreateEventComponent6,renderType_CreateEventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateEventComponent7 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_CreateEventComponent7,renderType_CreateEventComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = (<View_CreateEventComponent0>this.parentView)._NgForm_7_3.context.form.get('imageUrl').value;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import39.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}