/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/events/event-thumbnail.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import9 from '../../node_modules/@angular/common/src/directives/ng_style.ngfactory';
import * as import10 from '../../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/common/src/pipes/uppercase_pipe';
import * as import13 from '@angular/common/src/pipes/date_pipe';
import * as import14 from '@angular/common/src/pipes/number_pipe';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/core/src/i18n/tokens';
import * as import22 from '@angular/common/src/directives/ng_switch';
import * as import23 from '@angular/common/src/directives/ng_style';
import * as import24 from '@angular/router/src/directives/router_link';
export class Wrapper_EventThumbnailComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EventThumbnailComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.EventThumbnailComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_event(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.event = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EventThumbnailComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_EventThumbnailComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.EventThumbnailComponent>;
  _EventThumbnailComponent_0_3:Wrapper_EventThumbnailComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventThumbnailComponent_Host0,renderType_EventThumbnailComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'event-thumbnail',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EventThumbnailComponent0(this.viewUtils,this,0,this._el_0);
    this._EventThumbnailComponent_0_3 = new Wrapper_EventThumbnailComponent();
    this.compView_0.create(this._EventThumbnailComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EventThumbnailComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EventThumbnailComponent) && (0 === requestNodeIndex))) { return this._EventThumbnailComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EventThumbnailComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EventThumbnailComponentNgFactory:import7.ComponentFactory<import0.EventThumbnailComponent> = new import7.ComponentFactory<import0.EventThumbnailComponent>('event-thumbnail',View_EventThumbnailComponent_Host0,import0.EventThumbnailComponent);
const styles_EventThumbnailComponent:any[] = ['.pad-left[_ngcontent-%COMP%] { margin-left: 10px; }\n    .thumbnail[_ngcontent-%COMP%] { min-height: 210px; }\n    .well[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] { color: #bbb; }\n    .thumbnail[_ngcontent-%COMP%] { min-height: 210px; }'];
var renderType_EventThumbnailComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_EventThumbnailComponent,{});
export class View_EventThumbnailComponent0 extends import2.AppView<import0.EventThumbnailComponent> {
  _text_0:any;
  _el_1:any;
  _RouterLink_1_3:import8.Wrapper_RouterLink;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _NgStyle_9_3:import9.Wrapper_NgStyle;
  _NgSwitch_9_4:import10.Wrapper_NgSwitch;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import11.ViewContainer;
  _TemplateRef_11_5:any;
  _NgSwitchCase_11_6:import10.Wrapper_NgSwitchCase;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import11.ViewContainer;
  _TemplateRef_13_5:any;
  _NgSwitchCase_13_6:import10.Wrapper_NgSwitchCase;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _vc_15:import11.ViewContainer;
  _TemplateRef_15_5:any;
  _NgSwitchDefault_15_6:import10.Wrapper_NgSwitchDefault;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _arr_46:any;
  /*private*/ _expr_47:any;
  _pipe_uppercase_0:import12.UpperCasePipe;
  _pipe_uppercase_0_0:any;
  /*private*/ _expr_50:any;
  _pipe_date_1:import13.DatePipe;
  _pipe_date_1_0:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  _pipe_currency_2:import14.CurrencyPipe;
  _pipe_currency_2_0:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventThumbnailComponent0,renderType_EventThumbnailComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
    this._arr_46 = import3.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._expr_47 = import1.UNINITIALIZED;
    this._expr_50 = import1.UNINITIALIZED;
    this._expr_53 = import1.UNINITIALIZED;
    this._expr_54 = import1.UNINITIALIZED;
    this._expr_57 = import1.UNINITIALIZED;
    this._expr_58 = import1.UNINITIALIZED;
    this._expr_59 = import1.UNINITIALIZED;
    this._expr_60 = import1.UNINITIALIZED;
    this._expr_61 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','well hoverwell thumbnail'),(null as any));
    this._RouterLink_1_3 = new import8.Wrapper_RouterLink(this.parentView.injectorGet(import15.Router,this.parentIndex),this.parentView.injectorGet(import16.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import17.LocationStrategy,this.parentIndex));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgStyle_9_3 = new import9.Wrapper_NgStyle(this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_9),this.renderer);
    this._NgSwitch_9_4 = new import10.Wrapper_NgSwitch();
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_11 = new import11.ViewContainer(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import20.TemplateRef_(this,11,this._anchor_11);
    this._NgSwitchCase_11_6 = new import10.Wrapper_NgSwitchCase(this._vc_11.vcRef,this._TemplateRef_11_5,this._NgSwitch_9_4.context);
    this._text_12 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_13 = new import11.ViewContainer(13,9,this,this._anchor_13);
    this._TemplateRef_13_5 = new import20.TemplateRef_(this,13,this._anchor_13);
    this._NgSwitchCase_13_6 = new import10.Wrapper_NgSwitchCase(this._vc_13.vcRef,this._TemplateRef_13_5,this._NgSwitch_9_4.context);
    this._text_14 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_15 = new import11.ViewContainer(15,9,this,this._anchor_15);
    this._TemplateRef_15_5 = new import20.TemplateRef_(this,15,this._anchor_15);
    this._NgSwitchDefault_15_6 = new import10.Wrapper_NgSwitchDefault(this._vc_15.vcRef,this._TemplateRef_15_5,this._NgSwitch_9_4.context);
    this._text_16 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_21,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_21,'span',new import3.InlineArray2(2,'class','pad-left'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'',(null as any));
    this._text_28 = this.renderer.createText(this._el_21,'\n      ',(null as any));
    this._text_29 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_1,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'',(null as any));
    this._text_32 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_1,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_1));
    this._pipe_uppercase_0 = new import12.UpperCasePipe();
    this._pipe_uppercase_0_0 = import3.pureProxy1(this._pipe_uppercase_0.transform.bind(this._pipe_uppercase_0));
    this._pipe_date_1 = new import13.DatePipe(this.parentView.injectorGet(import21.LOCALE_ID,this.parentIndex));
    this._pipe_date_1_0 = import3.pureProxy2(this._pipe_date_1.transform.bind(this._pipe_date_1));
    this._pipe_currency_2 = new import14.CurrencyPipe(this.parentView.injectorGet(import21.LOCALE_ID,this.parentIndex));
    this._pipe_currency_2_0 = import3.pureProxy3(this._pipe_currency_2.transform.bind(this._pipe_currency_2));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import22.NgSwitchCase) && (11 === requestNodeIndex))) { return this._NgSwitchCase_11_6.context; }
    if (((token === import20.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import22.NgSwitchCase) && (13 === requestNodeIndex))) { return this._NgSwitchCase_13_6.context; }
    if (((token === import20.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import22.NgSwitchDefault) && (15 === requestNodeIndex))) { return this._NgSwitchDefault_15_6.context; }
    if (((token === import23.NgStyle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgStyle_9_3.context; }
    if (((token === import22.NgSwitch) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgSwitch_9_4.context; }
    if (((token === import24.RouterLink) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._RouterLink_1_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    const currVal_1_0_0:any = this._arr_46('/events',this.context.event.id);
    this._RouterLink_1_3.check_routerLink(currVal_1_0_0,throwOnChange,false);
    this._RouterLink_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    const currVal_9_0_0:any = this.context.getStartTimeStyle();
    this._NgStyle_9_3.check_ngStyle(currVal_9_0_0,throwOnChange,false);
    this._NgStyle_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = ((this.context.event == null)? (null as any): this.context.event.time);
    this._NgSwitch_9_4.check_ngSwitch(currVal_9_1_0,throwOnChange,false);
    this._NgSwitch_9_4.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_11_0_0:any = '8:00 am';
    this._NgSwitchCase_11_6.check_ngSwitchCase(currVal_11_0_0,throwOnChange,false);
    this._NgSwitchCase_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    const currVal_13_0_0:any = '10:00 am';
    this._NgSwitchCase_13_6.check_ngSwitchCase(currVal_13_0_0,throwOnChange,false);
    this._NgSwitchCase_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    this._NgSwitchDefault_15_6.ngDoCheck(this,this._anchor_15,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_15.detectChangesInNestedViews(throwOnChange);
    valUnwrapper.reset();
    const currVal_47:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_uppercase_0_0,this._pipe_uppercase_0.transform)(((this.context.event == null)? (null as any): this.context.event.name))),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_47,currVal_47))) {
      this.renderer.setText(this._text_4,currVal_47);
      this._expr_47 = currVal_47;
    }
    valUnwrapper.reset();
    const currVal_50:any = import3.inlineInterpolate(1,'Date: ',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_1_0,this._pipe_date_1.transform)(((this.context.event == null)? (null as any): this.context.event.date),'shortDate')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_50,currVal_50))) {
      this.renderer.setText(this._text_7,currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_53:any = import3.inlineInterpolate(1,'Time: ',((this.context.event == null)? (null as any): this.context.event.time),'\n        ');
    if (import3.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setText(this._text_10,currVal_53);
      this._expr_53 = currVal_53;
    }
    valUnwrapper.reset();
    const currVal_54:any = import3.inlineInterpolate(1,'Price: ',valUnwrapper.unwrap(import3.castByValue(this._pipe_currency_2_0,this._pipe_currency_2.transform)(((this.context.event == null)? (null as any): this.context.event.price),'USD',true)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_54,currVal_54))) {
      this.renderer.setText(this._text_19,currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_57:boolean = !((this.context.event == null)? (null as any): this.context.event.location);
    if (import3.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementProperty(this._el_21,'hidden',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = import3.inlineInterpolate(1,'Location: ',((this.context.event == null)? (null as any): ((this.context.event.location == null)? (null as any): this.context.event.location.address)),'');
    if (import3.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setText(this._text_24,currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = import3.inlineInterpolate(2,'',((this.context.event == null)? (null as any): ((this.context.event.location == null)? (null as any): this.context.event.location.city)),', ',((this.context.event == null)? (null as any): ((this.context.event.location == null)? (null as any): this.context.event.location.country)),'');
    if (import3.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setText(this._text_27,currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:boolean = !((this.context.event == null)? (null as any): this.context.event.onlineUrl);
    if (import3.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementProperty(this._el_30,'hidden',currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = import3.inlineInterpolate(1,'\n        Online Url: ',((this.context.event == null)? (null as any): this.context.event.onlineUrl),'\n      ');
    if (import3.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setText(this._text_31,currVal_61);
      this._expr_61 = currVal_61;
    }
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this._vc_13.destroyNestedViews();
    this._vc_15.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 11)) { return new View_EventThumbnailComponent1(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    if ((nodeIndex == 13)) { return new View_EventThumbnailComponent2(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 15)) { return new View_EventThumbnailComponent3(this.viewUtils,this,15,this._anchor_15,this._vc_15); }
    return (null as any);
  }
  handleEvent_1(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_1_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_EventThumbnailComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_EventThumbnailComponent1,renderType_EventThumbnailComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'(Early Start)',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_EventThumbnailComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_EventThumbnailComponent2,renderType_EventThumbnailComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'(Late Start)',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_EventThumbnailComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_EventThumbnailComponent3,renderType_EventThumbnailComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'(Normal Start)',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}