/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/events/event-details/create-session.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import9 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import10 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import14 from '../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import15 from '../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import16 from '../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import18 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from '@angular/forms/src/directives/default_value_accessor';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/common/src/directives/ng_class';
import * as import28 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import29 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import30 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import31 from '@angular/forms/src/directives/control_container';
export class Wrapper_CreateSessionComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CreateSessionComponent;
  /*private*/ _changed:boolean;
  subscription0:any;
  subscription1:any;
  constructor() {
    this._changed = false;
    this.context = new import0.CreateSessionComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.saveNewSession.subscribe(_eventHandler.bind(view,'saveNewSession'))); }
    if (emit1) { (this.subscription1 = this.context.cancelAddSession.subscribe(_eventHandler.bind(view,'cancelAddSession'))); }
  }
}
var renderType_CreateSessionComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CreateSessionComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CreateSessionComponent>;
  _CreateSessionComponent_0_3:Wrapper_CreateSessionComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreateSessionComponent_Host0,renderType_CreateSessionComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'create-session',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CreateSessionComponent0(this.viewUtils,this,0,this._el_0);
    this._CreateSessionComponent_0_3 = new Wrapper_CreateSessionComponent();
    this.compView_0.create(this._CreateSessionComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CreateSessionComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CreateSessionComponent) && (0 === requestNodeIndex))) { return this._CreateSessionComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CreateSessionComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CreateSessionComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CreateSessionComponentNgFactory:import7.ComponentFactory<import0.CreateSessionComponent> = new import7.ComponentFactory<import0.CreateSessionComponent>('create-session',View_CreateSessionComponent_Host0,import0.CreateSessionComponent);
const styles_CreateSessionComponent:any[] = ['em[_ngcontent-%COMP%] {float:right; color:#E05C65; padding-left:10px;}\n    .error[_ngcontent-%COMP%]   input[_ngcontent-%COMP%], .error[_ngcontent-%COMP%]   select[_ngcontent-%COMP%], .error[_ngcontent-%COMP%]   textarea[_ngcontent-%COMP%] {background-color:#E3C3C5;}\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-webkit-input-placeholder { color: #999; } \n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:-moz-placeholder { color: #999; }\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]::-moz-placeholder { color: #999; }\n    .error[_ngcontent-%COMP%]   [_ngcontent-%COMP%]:ms-input-placeholder  { color: #999; }'];
var renderType_CreateSessionComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CreateSessionComponent,{});
export class View_CreateSessionComponent0 extends import1.AppView<import0.CreateSessionComponent> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _FormGroupDirective_6_3:import8.Wrapper_FormGroupDirective;
  _ControlContainer_6_4:any;
  _NgControlStatusGroup_6_5:import9.Wrapper_NgControlStatusGroup;
  _text_7:any;
  _el_8:any;
  _NgClass_8_3:import10.Wrapper_NgClass;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import11.ViewContainer;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import12.Wrapper_NgIf;
  _text_14:any;
  _el_15:any;
  _DefaultValueAccessor_15_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_15_4:any[];
  _FormControlName_15_5:import14.Wrapper_FormControlName;
  _NgControl_15_6:any;
  _NgControlStatus_15_7:import9.Wrapper_NgControlStatus;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _NgClass_18_3:import10.Wrapper_NgClass;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _vc_23:import11.ViewContainer;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import12.Wrapper_NgIf;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_25_4:any[];
  _FormControlName_25_5:import14.Wrapper_FormControlName;
  _NgControl_25_6:any;
  _NgControlStatus_25_7:import9.Wrapper_NgControlStatus;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _NgClass_28_3:import10.Wrapper_NgClass;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _vc_33:import11.ViewContainer;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import12.Wrapper_NgIf;
  _text_34:any;
  _el_35:any;
  _SelectControlValueAccessor_35_3:import15.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_35_4:any[];
  _FormControlName_35_5:import14.Wrapper_FormControlName;
  _NgControl_35_6:any;
  _NgControlStatus_35_7:import9.Wrapper_NgControlStatus;
  _text_36:any;
  _el_37:any;
  _NgSelectOption_37_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_37_4:import16.Wrapper_NgSelectMultipleOption;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _NgSelectOption_40_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_40_4:import16.Wrapper_NgSelectMultipleOption;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _NgSelectOption_43_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_43_4:import16.Wrapper_NgSelectMultipleOption;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _NgSelectOption_46_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_46_4:import16.Wrapper_NgSelectMultipleOption;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _NgSelectOption_49_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_49_4:import16.Wrapper_NgSelectMultipleOption;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _NgClass_54_3:import10.Wrapper_NgClass;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _anchor_59:any;
  /*private*/ _vc_59:import11.ViewContainer;
  _TemplateRef_59_5:any;
  _NgIf_59_6:import12.Wrapper_NgIf;
  _text_60:any;
  _el_61:any;
  _SelectControlValueAccessor_61_3:import15.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_61_4:any[];
  _FormControlName_61_5:import14.Wrapper_FormControlName;
  _NgControl_61_6:any;
  _NgControlStatus_61_7:import9.Wrapper_NgControlStatus;
  _text_62:any;
  _el_63:any;
  _NgSelectOption_63_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_63_4:import16.Wrapper_NgSelectMultipleOption;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _NgSelectOption_66_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_66_4:import16.Wrapper_NgSelectMultipleOption;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _NgSelectOption_69_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_69_4:import16.Wrapper_NgSelectMultipleOption;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _NgSelectOption_72_3:import15.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_72_4:import16.Wrapper_NgSelectMultipleOption;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _NgClass_77_3:import10.Wrapper_NgClass;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _anchor_82:any;
  /*private*/ _vc_82:import11.ViewContainer;
  _TemplateRef_82_5:any;
  _NgIf_82_6:import12.Wrapper_NgIf;
  _text_83:any;
  _anchor_84:any;
  /*private*/ _vc_84:import11.ViewContainer;
  _TemplateRef_84_5:any;
  _NgIf_84_6:import12.Wrapper_NgIf;
  _text_85:any;
  _el_86:any;
  _DefaultValueAccessor_86_3:import13.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_86_4:any[];
  _FormControlName_86_5:import14.Wrapper_FormControlName;
  _NgControl_86_6:any;
  _NgControlStatus_86_7:import9.Wrapper_NgControlStatus;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _map_166:any;
  _map_167:any;
  _map_168:any;
  _map_169:any;
  _map_170:any;
  /*private*/ _expr_171:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CreateSessionComponent0,renderType_CreateSessionComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_166 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_167 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_168 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_169 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._map_170 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {error: p0};
    });
    this._expr_171 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'Create Session',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'form',new import3.InlineArray2(2,'autocomplete','off'),(null as any));
    this._FormGroupDirective_6_3 = new import8.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_6_4 = this._FormGroupDirective_6_3.context;
    this._NgControlStatusGroup_6_5 = new import9.Wrapper_NgControlStatusGroup(this._ControlContainer_6_4);
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_8_3 = new import10.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'label',new import3.InlineArray2(2,'for','sessionName'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Session Name:',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_8,(null as any));
    this._vc_13 = new import11.ViewContainer(13,8,this,this._anchor_13);
    this._TemplateRef_13_5 = new import20.TemplateRef_(this,13,this._anchor_13);
    this._NgIf_13_6 = new import12.Wrapper_NgIf(this._vc_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_8,'input',new import3.InlineArray16(10,'class','form-control','formControlName','name','id','sessionName','placeholder','session name...','type','text'),(null as any));
    this._DefaultValueAccessor_15_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_15));
    this._NG_VALUE_ACCESSOR_15_4 = [this._DefaultValueAccessor_15_3.context];
    this._FormControlName_15_5 = new import14.Wrapper_FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_15_4);
    this._NgControl_15_6 = this._FormControlName_15_5.context;
    this._NgControlStatus_15_7 = new import9.Wrapper_NgControlStatus(this._NgControl_15_6);
    this._text_16 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_18_3 = new import10.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'label',new import3.InlineArray2(2,'for','eventDate'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Presenter:',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._vc_23 = new import11.ViewContainer(23,18,this,this._anchor_23);
    this._TemplateRef_23_5 = new import20.TemplateRef_(this,23,this._anchor_23);
    this._NgIf_23_6 = new import12.Wrapper_NgIf(this._vc_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_18,'input',new import3.InlineArray16(10,'class','form-control','formControlName','presenter','id','presenter','placeholder','presenter...','type','text'),(null as any));
    this._DefaultValueAccessor_25_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_25));
    this._NG_VALUE_ACCESSOR_25_4 = [this._DefaultValueAccessor_25_3.context];
    this._FormControlName_25_5 = new import14.Wrapper_FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_4);
    this._NgControl_25_6 = this._FormControlName_25_5.context;
    this._NgControlStatus_25_7 = new import9.Wrapper_NgControlStatus(this._NgControl_25_6);
    this._text_26 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_28_3 = new import10.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_28,'\n      ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'label',new import3.InlineArray2(2,'for','duration'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Duration:',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n      ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_28,(null as any));
    this._vc_33 = new import11.ViewContainer(33,28,this,this._anchor_33);
    this._TemplateRef_33_5 = new import20.TemplateRef_(this,33,this._anchor_33);
    this._NgIf_33_6 = new import12.Wrapper_NgIf(this._vc_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_28,'\n      ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_28,'select',new import3.InlineArray4(4,'class','form-control','formControlName','duration'),(null as any));
    this._SelectControlValueAccessor_35_3 = new import15.Wrapper_SelectControlValueAccessor(this.renderer,new import19.ElementRef(this._el_35));
    this._NG_VALUE_ACCESSOR_35_4 = [this._SelectControlValueAccessor_35_3.context];
    this._FormControlName_35_5 = new import14.Wrapper_FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_35_4);
    this._NgControl_35_6 = this._FormControlName_35_5.context;
    this._NgControlStatus_35_7 = new import9.Wrapper_NgControlStatus(this._NgControl_35_6);
    this._text_36 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'option',new import3.InlineArray2(2,'value',''),(null as any));
    this._NgSelectOption_37_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_37),this.renderer,this._SelectControlValueAccessor_35_3.context);
    this._NgSelectMultipleOption_37_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_37),this.renderer,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'select duration...',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'option',new import3.InlineArray2(2,'value','1'),(null as any));
    this._NgSelectOption_40_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_40),this.renderer,this._SelectControlValueAccessor_35_3.context);
    this._NgSelectMultipleOption_40_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_40),this.renderer,(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Half Hour',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,this._el_35,'option',new import3.InlineArray2(2,'value','2'),(null as any));
    this._NgSelectOption_43_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_43),this.renderer,this._SelectControlValueAccessor_35_3.context);
    this._NgSelectMultipleOption_43_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_43),this.renderer,(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'1 Hour',(null as any));
    this._text_45 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_35,'option',new import3.InlineArray2(2,'value','3'),(null as any));
    this._NgSelectOption_46_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_46),this.renderer,this._SelectControlValueAccessor_35_3.context);
    this._NgSelectMultipleOption_46_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_46),this.renderer,(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Half Day',(null as any));
    this._text_48 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_35,'option',new import3.InlineArray2(2,'value','4'),(null as any));
    this._NgSelectOption_49_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_49),this.renderer,this._SelectControlValueAccessor_35_3.context);
    this._NgSelectMultipleOption_49_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_49),this.renderer,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'Full Day',(null as any));
    this._text_51 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._text_52 = this.renderer.createText(this._el_28,'\n    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_54_3 = new import10.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_54),this.renderer);
    this._text_55 = this.renderer.createText(this._el_54,'\n      ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_54,'label',new import3.InlineArray2(2,'for','level'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Level:',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n      ',(null as any));
    this._anchor_59 = this.renderer.createTemplateAnchor(this._el_54,(null as any));
    this._vc_59 = new import11.ViewContainer(59,54,this,this._anchor_59);
    this._TemplateRef_59_5 = new import20.TemplateRef_(this,59,this._anchor_59);
    this._NgIf_59_6 = new import12.Wrapper_NgIf(this._vc_59.vcRef,this._TemplateRef_59_5);
    this._text_60 = this.renderer.createText(this._el_54,'\n      ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_54,'select',new import3.InlineArray8(6,'class','form-control','formControlName','level','ngControl','level'),(null as any));
    this._SelectControlValueAccessor_61_3 = new import15.Wrapper_SelectControlValueAccessor(this.renderer,new import19.ElementRef(this._el_61));
    this._NG_VALUE_ACCESSOR_61_4 = [this._SelectControlValueAccessor_61_3.context];
    this._FormControlName_61_5 = new import14.Wrapper_FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_61_4);
    this._NgControl_61_6 = this._FormControlName_61_5.context;
    this._NgControlStatus_61_7 = new import9.Wrapper_NgControlStatus(this._NgControl_61_6);
    this._text_62 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_61,'option',new import3.InlineArray2(2,'value',''),(null as any));
    this._NgSelectOption_63_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_63),this.renderer,this._SelectControlValueAccessor_61_3.context);
    this._NgSelectMultipleOption_63_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_63),this.renderer,(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'select duration...',(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_61,'option',new import3.InlineArray2(2,'value','Beginner'),(null as any));
    this._NgSelectOption_66_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_66),this.renderer,this._SelectControlValueAccessor_61_3.context);
    this._NgSelectMultipleOption_66_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_66),this.renderer,(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'Beginner',(null as any));
    this._text_68 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_61,'option',new import3.InlineArray2(2,'value','Intermediate'),(null as any));
    this._NgSelectOption_69_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_69),this.renderer,this._SelectControlValueAccessor_61_3.context);
    this._NgSelectMultipleOption_69_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_69),this.renderer,(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Intermediate',(null as any));
    this._text_71 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_61,'option',new import3.InlineArray2(2,'value','Advanced'),(null as any));
    this._NgSelectOption_72_3 = new import15.Wrapper_NgSelectOption(new import19.ElementRef(this._el_72),this.renderer,this._SelectControlValueAccessor_61_3.context);
    this._NgSelectMultipleOption_72_4 = new import16.Wrapper_NgSelectMultipleOption(new import19.ElementRef(this._el_72),this.renderer,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Advanced',(null as any));
    this._text_74 = this.renderer.createText(this._el_61,'\n      ',(null as any));
    this._text_75 = this.renderer.createText(this._el_54,'\n    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_6,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgClass_77_3 = new import10.Wrapper_NgClass(this.parentView.injectorGet(import17.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import18.KeyValueDiffers,this.parentIndex),new import19.ElementRef(this._el_77),this.renderer);
    this._text_78 = this.renderer.createText(this._el_77,'\n      ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_77,'label',new import3.InlineArray2(2,'for','abstract'),(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'Abstract:',(null as any));
    this._text_81 = this.renderer.createText(this._el_77,'\n      ',(null as any));
    this._anchor_82 = this.renderer.createTemplateAnchor(this._el_77,(null as any));
    this._vc_82 = new import11.ViewContainer(82,77,this,this._anchor_82);
    this._TemplateRef_82_5 = new import20.TemplateRef_(this,82,this._anchor_82);
    this._NgIf_82_6 = new import12.Wrapper_NgIf(this._vc_82.vcRef,this._TemplateRef_82_5);
    this._text_83 = this.renderer.createText(this._el_77,'\n      ',(null as any));
    this._anchor_84 = this.renderer.createTemplateAnchor(this._el_77,(null as any));
    this._vc_84 = new import11.ViewContainer(84,77,this,this._anchor_84);
    this._TemplateRef_84_5 = new import20.TemplateRef_(this,84,this._anchor_84);
    this._NgIf_84_6 = new import12.Wrapper_NgIf(this._vc_84.vcRef,this._TemplateRef_84_5);
    this._text_85 = this.renderer.createText(this._el_77,'\n      ',(null as any));
    this._el_86 = import3.createRenderElement(this.renderer,this._el_77,'textarea',new import3.InlineArray16(10,'class','form-control','formControlName','abstract','id','abstract','placeholder','abstract...','rows','3'),(null as any));
    this._DefaultValueAccessor_86_3 = new import13.Wrapper_DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_86));
    this._NG_VALUE_ACCESSOR_86_4 = [this._DefaultValueAccessor_86_3.context];
    this._FormControlName_86_5 = new import14.Wrapper_FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_86_4);
    this._NgControl_86_6 = this._FormControlName_86_5.context;
    this._NgControlStatus_86_7 = new import9.Wrapper_NgControlStatus(this._NgControl_86_6);
    this._text_87 = this.renderer.createText(this._el_77,'\n    ',(null as any));
    this._text_88 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'Save',(null as any));
    this._text_91 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_92 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray4(4,'class','btn btn-default','type','button'),(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'Cancel',(null as any));
    this._text_94 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._text_95 = this.renderer.createText(this._el_4,'\n',(null as any));
    this._text_96 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_6));
    this._FormGroupDirective_6_3.subscribe(this,this.eventHandler(this.handleEvent_6),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_25,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_25));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_35,new import3.InlineArray4(4,'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_35));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_61,new import3.InlineArray4(4,'change',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_61));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_86,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_86));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_92,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_92));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._anchor_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._anchor_82,
      this._text_83,
      this._anchor_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import21.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import22.DefaultValueAccessor) && (15 === requestNodeIndex))) { return this._DefaultValueAccessor_15_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (15 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_15_4; }
    if (((token === import24.FormControlName) && (15 === requestNodeIndex))) { return this._FormControlName_15_5.context; }
    if (((token === import25.NgControl) && (15 === requestNodeIndex))) { return this._NgControl_15_6; }
    if (((token === import26.NgControlStatus) && (15 === requestNodeIndex))) { return this._NgControlStatus_15_7.context; }
    if (((token === import27.NgClass) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._NgClass_8_3.context; }
    if (((token === import20.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import21.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import22.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_4; }
    if (((token === import24.FormControlName) && (25 === requestNodeIndex))) { return this._FormControlName_25_5.context; }
    if (((token === import25.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_6; }
    if (((token === import26.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_7.context; }
    if (((token === import27.NgClass) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgClass_18_3.context; }
    if (((token === import20.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import21.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6.context; }
    if (((token === import28.NgSelectOption) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgSelectOption_37_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgSelectMultipleOption_37_4.context; }
    if (((token === import28.NgSelectOption) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgSelectOption_40_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._NgSelectMultipleOption_40_4.context; }
    if (((token === import28.NgSelectOption) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._NgSelectOption_43_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._NgSelectMultipleOption_43_4.context; }
    if (((token === import28.NgSelectOption) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._NgSelectOption_46_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._NgSelectMultipleOption_46_4.context; }
    if (((token === import28.NgSelectOption) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgSelectOption_49_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgSelectMultipleOption_49_4.context; }
    if (((token === import28.SelectControlValueAccessor) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._SelectControlValueAccessor_35_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NG_VALUE_ACCESSOR_35_4; }
    if (((token === import24.FormControlName) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._FormControlName_35_5.context; }
    if (((token === import25.NgControl) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgControl_35_6; }
    if (((token === import26.NgControlStatus) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._NgControlStatus_35_7.context; }
    if (((token === import27.NgClass) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgClass_28_3.context; }
    if (((token === import20.TemplateRef) && (59 === requestNodeIndex))) { return this._TemplateRef_59_5; }
    if (((token === import21.NgIf) && (59 === requestNodeIndex))) { return this._NgIf_59_6.context; }
    if (((token === import28.NgSelectOption) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NgSelectOption_63_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._NgSelectMultipleOption_63_4.context; }
    if (((token === import28.NgSelectOption) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._NgSelectOption_66_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._NgSelectMultipleOption_66_4.context; }
    if (((token === import28.NgSelectOption) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._NgSelectOption_69_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._NgSelectMultipleOption_69_4.context; }
    if (((token === import28.NgSelectOption) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._NgSelectOption_72_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._NgSelectMultipleOption_72_4.context; }
    if (((token === import28.SelectControlValueAccessor) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._SelectControlValueAccessor_61_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NG_VALUE_ACCESSOR_61_4; }
    if (((token === import24.FormControlName) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._FormControlName_61_5.context; }
    if (((token === import25.NgControl) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NgControl_61_6; }
    if (((token === import26.NgControlStatus) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._NgControlStatus_61_7.context; }
    if (((token === import27.NgClass) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._NgClass_54_3.context; }
    if (((token === import20.TemplateRef) && (82 === requestNodeIndex))) { return this._TemplateRef_82_5; }
    if (((token === import21.NgIf) && (82 === requestNodeIndex))) { return this._NgIf_82_6.context; }
    if (((token === import20.TemplateRef) && (84 === requestNodeIndex))) { return this._TemplateRef_84_5; }
    if (((token === import21.NgIf) && (84 === requestNodeIndex))) { return this._NgIf_84_6.context; }
    if (((token === import22.DefaultValueAccessor) && (86 === requestNodeIndex))) { return this._DefaultValueAccessor_86_3.context; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (86 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_86_4; }
    if (((token === import24.FormControlName) && (86 === requestNodeIndex))) { return this._FormControlName_86_5.context; }
    if (((token === import25.NgControl) && (86 === requestNodeIndex))) { return this._NgControl_86_6; }
    if (((token === import26.NgControlStatus) && (86 === requestNodeIndex))) { return this._NgControlStatus_86_7.context; }
    if (((token === import27.NgClass) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 87)))) { return this._NgClass_77_3.context; }
    if (((token === import30.FormGroupDirective) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._FormGroupDirective_6_3.context; }
    if (((token === import31.ControlContainer) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._ControlContainer_6_4; }
    if (((token === import26.NgControlStatusGroup) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._NgControlStatusGroup_6_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_6_0_0:any = this.context.newSessionForm;
    this._FormGroupDirective_6_3.check_form(currVal_6_0_0,throwOnChange,false);
    this._FormGroupDirective_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._NgControlStatusGroup_6_5.ngDoCheck(this,this._el_6,throwOnChange);
    const currVal_8_0_0:any = 'form-group';
    this._NgClass_8_3.check_klass(currVal_8_0_0,throwOnChange,false);
    const currVal_8_0_1:any = this._map_166((this.context.name.invalid && this.context.name.dirty));
    this._NgClass_8_3.check_ngClass(currVal_8_0_1,throwOnChange,false);
    this._NgClass_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    const currVal_13_0_0:any = (this.context.name.invalid && this.context.name.dirty);
    this._NgIf_13_6.check_ngIf(currVal_13_0_0,throwOnChange,false);
    this._NgIf_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    this._DefaultValueAccessor_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = 'name';
    this._FormControlName_15_5.check_name(currVal_15_1_0,throwOnChange,false);
    this._FormControlName_15_5.ngDoCheck(this,this._el_15,throwOnChange);
    this._NgControlStatus_15_7.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_18_0_0:any = 'form-group';
    this._NgClass_18_3.check_klass(currVal_18_0_0,throwOnChange,false);
    const currVal_18_0_1:any = this._map_167((this.context.presenter.invalid && this.context.presenter.dirty));
    this._NgClass_18_3.check_ngClass(currVal_18_0_1,throwOnChange,false);
    this._NgClass_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    const currVal_23_0_0:any = (this.context.presenter.invalid && this.context.presenter.dirty);
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.ngDoCheck(this,this._anchor_23,throwOnChange);
    this._DefaultValueAccessor_25_3.ngDoCheck(this,this._el_25,throwOnChange);
    const currVal_25_1_0:any = 'presenter';
    this._FormControlName_25_5.check_name(currVal_25_1_0,throwOnChange,false);
    this._FormControlName_25_5.ngDoCheck(this,this._el_25,throwOnChange);
    this._NgControlStatus_25_7.ngDoCheck(this,this._el_25,throwOnChange);
    const currVal_28_0_0:any = 'form-group';
    this._NgClass_28_3.check_klass(currVal_28_0_0,throwOnChange,false);
    const currVal_28_0_1:any = this._map_168((this.context.duration.invalid && this.context.duration.dirty));
    this._NgClass_28_3.check_ngClass(currVal_28_0_1,throwOnChange,false);
    this._NgClass_28_3.ngDoCheck(this,this._el_28,throwOnChange);
    const currVal_33_0_0:any = (this.context.duration.invalid && this.context.duration.dirty);
    this._NgIf_33_6.check_ngIf(currVal_33_0_0,throwOnChange,false);
    this._NgIf_33_6.ngDoCheck(this,this._anchor_33,throwOnChange);
    this._SelectControlValueAccessor_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_35_1_0:any = 'duration';
    this._FormControlName_35_5.check_name(currVal_35_1_0,throwOnChange,false);
    this._FormControlName_35_5.ngDoCheck(this,this._el_35,throwOnChange);
    this._NgControlStatus_35_7.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_37_0_0:any = '';
    this._NgSelectOption_37_3.check_value(currVal_37_0_0,throwOnChange,false);
    this._NgSelectOption_37_3.ngDoCheck(this,this._el_37,throwOnChange);
    const currVal_37_1_0:any = '';
    this._NgSelectMultipleOption_37_4.check_value(currVal_37_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_37_4.ngDoCheck(this,this._el_37,throwOnChange);
    const currVal_40_0_0:any = '1';
    this._NgSelectOption_40_3.check_value(currVal_40_0_0,throwOnChange,false);
    this._NgSelectOption_40_3.ngDoCheck(this,this._el_40,throwOnChange);
    const currVal_40_1_0:any = '1';
    this._NgSelectMultipleOption_40_4.check_value(currVal_40_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_40_4.ngDoCheck(this,this._el_40,throwOnChange);
    const currVal_43_0_0:any = '2';
    this._NgSelectOption_43_3.check_value(currVal_43_0_0,throwOnChange,false);
    this._NgSelectOption_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_43_1_0:any = '2';
    this._NgSelectMultipleOption_43_4.check_value(currVal_43_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_43_4.ngDoCheck(this,this._el_43,throwOnChange);
    const currVal_46_0_0:any = '3';
    this._NgSelectOption_46_3.check_value(currVal_46_0_0,throwOnChange,false);
    this._NgSelectOption_46_3.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_46_1_0:any = '3';
    this._NgSelectMultipleOption_46_4.check_value(currVal_46_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_46_4.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_49_0_0:any = '4';
    this._NgSelectOption_49_3.check_value(currVal_49_0_0,throwOnChange,false);
    this._NgSelectOption_49_3.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_49_1_0:any = '4';
    this._NgSelectMultipleOption_49_4.check_value(currVal_49_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_49_4.ngDoCheck(this,this._el_49,throwOnChange);
    const currVal_54_0_0:any = 'form-group';
    this._NgClass_54_3.check_klass(currVal_54_0_0,throwOnChange,false);
    const currVal_54_0_1:any = this._map_169((this.context.level.invalid && this.context.level.dirty));
    this._NgClass_54_3.check_ngClass(currVal_54_0_1,throwOnChange,false);
    this._NgClass_54_3.ngDoCheck(this,this._el_54,throwOnChange);
    const currVal_59_0_0:any = (this.context.level.invalid && this.context.level.dirty);
    this._NgIf_59_6.check_ngIf(currVal_59_0_0,throwOnChange,false);
    this._NgIf_59_6.ngDoCheck(this,this._anchor_59,throwOnChange);
    this._SelectControlValueAccessor_61_3.ngDoCheck(this,this._el_61,throwOnChange);
    const currVal_61_1_0:any = 'level';
    this._FormControlName_61_5.check_name(currVal_61_1_0,throwOnChange,false);
    this._FormControlName_61_5.ngDoCheck(this,this._el_61,throwOnChange);
    this._NgControlStatus_61_7.ngDoCheck(this,this._el_61,throwOnChange);
    const currVal_63_0_0:any = '';
    this._NgSelectOption_63_3.check_value(currVal_63_0_0,throwOnChange,false);
    this._NgSelectOption_63_3.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_63_1_0:any = '';
    this._NgSelectMultipleOption_63_4.check_value(currVal_63_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_63_4.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_66_0_0:any = 'Beginner';
    this._NgSelectOption_66_3.check_value(currVal_66_0_0,throwOnChange,false);
    this._NgSelectOption_66_3.ngDoCheck(this,this._el_66,throwOnChange);
    const currVal_66_1_0:any = 'Beginner';
    this._NgSelectMultipleOption_66_4.check_value(currVal_66_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_66_4.ngDoCheck(this,this._el_66,throwOnChange);
    const currVal_69_0_0:any = 'Intermediate';
    this._NgSelectOption_69_3.check_value(currVal_69_0_0,throwOnChange,false);
    this._NgSelectOption_69_3.ngDoCheck(this,this._el_69,throwOnChange);
    const currVal_69_1_0:any = 'Intermediate';
    this._NgSelectMultipleOption_69_4.check_value(currVal_69_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_69_4.ngDoCheck(this,this._el_69,throwOnChange);
    const currVal_72_0_0:any = 'Advanced';
    this._NgSelectOption_72_3.check_value(currVal_72_0_0,throwOnChange,false);
    this._NgSelectOption_72_3.ngDoCheck(this,this._el_72,throwOnChange);
    const currVal_72_1_0:any = 'Advanced';
    this._NgSelectMultipleOption_72_4.check_value(currVal_72_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_72_4.ngDoCheck(this,this._el_72,throwOnChange);
    const currVal_77_0_0:any = 'form-group';
    this._NgClass_77_3.check_klass(currVal_77_0_0,throwOnChange,false);
    const currVal_77_0_1:any = this._map_170((this.context.abstract.invalid && this.context.abstract.dirty));
    this._NgClass_77_3.check_ngClass(currVal_77_0_1,throwOnChange,false);
    this._NgClass_77_3.ngDoCheck(this,this._el_77,throwOnChange);
    const currVal_82_0_0:any = ((this.context.abstract.invalid && this.context.abstract.dirty) && this.context.abstract.errors['required']);
    this._NgIf_82_6.check_ngIf(currVal_82_0_0,throwOnChange,false);
    this._NgIf_82_6.ngDoCheck(this,this._anchor_82,throwOnChange);
    const currVal_84_0_0:any = ((this.context.abstract.invalid && this.context.abstract.dirty) && this.context.abstract.errors['restrictedWords']);
    this._NgIf_84_6.check_ngIf(currVal_84_0_0,throwOnChange,false);
    this._NgIf_84_6.ngDoCheck(this,this._anchor_84,throwOnChange);
    this._DefaultValueAccessor_86_3.ngDoCheck(this,this._el_86,throwOnChange);
    const currVal_86_1_0:any = 'abstract';
    this._FormControlName_86_5.check_name(currVal_86_1_0,throwOnChange,false);
    this._FormControlName_86_5.ngDoCheck(this,this._el_86,throwOnChange);
    this._NgControlStatus_86_7.ngDoCheck(this,this._el_86,throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_23.detectChangesInNestedViews(throwOnChange);
    this._vc_33.detectChangesInNestedViews(throwOnChange);
    this._vc_59.detectChangesInNestedViews(throwOnChange);
    this._vc_82.detectChangesInNestedViews(throwOnChange);
    this._vc_84.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_6_5.checkHost(this,this,this._el_6,throwOnChange);
    this._NgControlStatus_15_7.checkHost(this,this,this._el_15,throwOnChange);
    this._NgControlStatus_25_7.checkHost(this,this,this._el_25,throwOnChange);
    this._NgControlStatus_35_7.checkHost(this,this,this._el_35,throwOnChange);
    this._NgControlStatus_61_7.checkHost(this,this,this._el_61,throwOnChange);
    this._NgControlStatus_86_7.checkHost(this,this,this._el_86,throwOnChange);
    const currVal_171:any = this.context.newSessionForm.invalid;
    if (import3.checkBinding(throwOnChange,this._expr_171,currVal_171)) {
      this.renderer.setElementProperty(this._el_89,'disabled',currVal_171);
      this._expr_171 = currVal_171;
    }
  }
  destroyInternal():void {
    this._vc_13.destroyNestedViews();
    this._vc_23.destroyNestedViews();
    this._vc_33.destroyNestedViews();
    this._vc_59.destroyNestedViews();
    this._vc_82.destroyNestedViews();
    this._vc_84.destroyNestedViews();
    this._FormControlName_15_5.ngOnDestroy();
    this._FormControlName_25_5.ngOnDestroy();
    this._NgSelectOption_37_3.ngOnDestroy();
    this._NgSelectMultipleOption_37_4.ngOnDestroy();
    this._NgSelectOption_40_3.ngOnDestroy();
    this._NgSelectMultipleOption_40_4.ngOnDestroy();
    this._NgSelectOption_43_3.ngOnDestroy();
    this._NgSelectMultipleOption_43_4.ngOnDestroy();
    this._NgSelectOption_46_3.ngOnDestroy();
    this._NgSelectMultipleOption_46_4.ngOnDestroy();
    this._NgSelectOption_49_3.ngOnDestroy();
    this._NgSelectMultipleOption_49_4.ngOnDestroy();
    this._FormControlName_35_5.ngOnDestroy();
    this._NgSelectOption_63_3.ngOnDestroy();
    this._NgSelectMultipleOption_63_4.ngOnDestroy();
    this._NgSelectOption_66_3.ngOnDestroy();
    this._NgSelectMultipleOption_66_4.ngOnDestroy();
    this._NgSelectOption_69_3.ngOnDestroy();
    this._NgSelectMultipleOption_69_4.ngOnDestroy();
    this._NgSelectOption_72_3.ngOnDestroy();
    this._NgSelectMultipleOption_72_4.ngOnDestroy();
    this._FormControlName_61_5.ngOnDestroy();
    this._FormControlName_86_5.ngOnDestroy();
    this._FormGroupDirective_6_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 13)) { return new View_CreateSessionComponent1(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 23)) { return new View_CreateSessionComponent2(this.viewUtils,this,23,this._anchor_23,this._vc_23); }
    if ((nodeIndex == 33)) { return new View_CreateSessionComponent3(this.viewUtils,this,33,this._anchor_33,this._vc_33); }
    if ((nodeIndex == 59)) { return new View_CreateSessionComponent4(this.viewUtils,this,59,this._anchor_59,this._vc_59); }
    if ((nodeIndex == 82)) { return new View_CreateSessionComponent5(this.viewUtils,this,82,this._anchor_82,this._vc_82); }
    if ((nodeIndex == 84)) { return new View_CreateSessionComponent6(this.viewUtils,this,84,this._anchor_84,this._vc_84); }
    return (null as any);
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_6_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.saveSession(this.context.newSessionForm.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_15_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_25(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_25_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_35(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_35_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_61(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._SelectControlValueAccessor_61_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_86(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_86_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_92(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.cancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_CreateSessionComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_CreateSessionComponent1,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_CreateSessionComponent2,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_CreateSessionComponent3,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_CreateSessionComponent4,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_CreateSessionComponent5,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Required',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_CreateSessionComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_CreateSessionComponent6,renderType_CreateSessionComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'em',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'Restricted words found: ',this.parentView.context.abstract.errors.restrictedWords,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}