/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/events/event-details/event-details.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../app/events/shared/event.service';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import12 from '@angular/common/src/pipes/uppercase_pipe';
import * as import13 from '@angular/common/src/pipes/date_pipe';
import * as import14 from '@angular/common/src/pipes/number_pipe';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/i18n/tokens';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '@angular/core/src/security';
import * as import19 from '../../../../app/events/event-details/session-list.component';
import * as import20 from './session-list.component.ngfactory';
import * as import21 from '../../../../app/user/auth.service';
import * as import22 from '../../../../app/events/event-details/voter.service';
import * as import23 from '../../../../app/events/event-details/create-session.component';
import * as import24 from './create-session.component.ngfactory';
export class Wrapper_EventDetailsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EventDetailsComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.EventDetailsComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EventDetailsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_EventDetailsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.EventDetailsComponent>;
  _EventDetailsComponent_0_3:Wrapper_EventDetailsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventDetailsComponent_Host0,renderType_EventDetailsComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EventDetailsComponent0(this.viewUtils,this,0,this._el_0);
    this._EventDetailsComponent_0_3 = new Wrapper_EventDetailsComponent(this.injectorGet(import8.EventService,this.parentIndex),this.injectorGet(import9.ActivatedRoute,this.parentIndex));
    this.compView_0.create(this._EventDetailsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EventDetailsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EventDetailsComponent) && (0 === requestNodeIndex))) { return this._EventDetailsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EventDetailsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EventDetailsComponentNgFactory:import7.ComponentFactory<import0.EventDetailsComponent> = new import7.ComponentFactory<import0.EventDetailsComponent>('ng-component',View_EventDetailsComponent_Host0,import0.EventDetailsComponent);
const styles_EventDetailsComponent:any[] = ['.container[_ngcontent-%COMP%] { padding-left:20px; padding-right:20px; }\n    .event-image[_ngcontent-%COMP%] { height:100px; }\n    a[_ngcontent-%COMP%] {cursor:pointer}'];
var renderType_EventDetailsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_EventDetailsComponent,{});
export class View_EventDetailsComponent0 extends import1.AppView<import0.EventDetailsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _anchor_90:any;
  /*private*/ _vc_90:import10.ViewContainer;
  _TemplateRef_90_5:any;
  _NgIf_90_6:import11.Wrapper_NgIf;
  _text_91:any;
  _anchor_92:any;
  /*private*/ _vc_92:import10.ViewContainer;
  _TemplateRef_92_5:any;
  _NgIf_92_6:import11.Wrapper_NgIf;
  _text_93:any;
  /*private*/ _expr_100:any;
  /*private*/ _expr_101:any;
  /*private*/ _expr_102:any;
  _pipe_uppercase_0:import12.UpperCasePipe;
  _pipe_uppercase_0_0:any;
  /*private*/ _expr_105:any;
  _pipe_date_1:import13.DatePipe;
  _pipe_date_1_0:any;
  /*private*/ _expr_108:any;
  /*private*/ _expr_109:any;
  _pipe_currency_2:import14.CurrencyPipe;
  _pipe_currency_2_0:any;
  /*private*/ _expr_112:any;
  /*private*/ _expr_113:any;
  /*private*/ _expr_114:any;
  /*private*/ _expr_115:any;
  /*private*/ _expr_116:any;
  /*private*/ _expr_117:any;
  /*private*/ _expr_118:any;
  /*private*/ _expr_119:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EventDetailsComponent0,renderType_EventDetailsComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_100 = import6.UNINITIALIZED;
    this._expr_101 = import6.UNINITIALIZED;
    this._expr_102 = import6.UNINITIALIZED;
    this._expr_105 = import6.UNINITIALIZED;
    this._expr_108 = import6.UNINITIALIZED;
    this._expr_109 = import6.UNINITIALIZED;
    this._expr_112 = import6.UNINITIALIZED;
    this._expr_113 = import6.UNINITIALIZED;
    this._expr_114 = import6.UNINITIALIZED;
    this._expr_115 = import6.UNINITIALIZED;
    this._expr_116 = import6.UNINITIALIZED;
    this._expr_117 = import6.UNINITIALIZED;
    this._expr_118 = import6.UNINITIALIZED;
    this._expr_119 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'class','event-image'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'div',new import3.InlineArray2(2,'class','col-md-11'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Date:',(null as any));
    this._text_20 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_15,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_22,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Time:',(null as any));
    this._text_25 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_15,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_27,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Price:',(null as any));
    this._text_30 = this.renderer.createText(this._el_27,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_13,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n      ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'address',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'strong',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Address:',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_35,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_35,'',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_35,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_43 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._text_44 = this.renderer.createText(this._el_13,'\n  ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_0,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_47 = this.renderer.createText(this._el_0,'\n\n\n\n  ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray4(4,'class','row','style','margin-bottom:10px'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n      ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'h3',new import3.InlineArray2(2,'style','margin:0'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Sessions',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','col-md-7'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n      ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_56,'div',new import3.InlineArray4(4,'class','btn-group btn-group-sm','style','margin-right:20px;margin-left:20px'),(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'\n        ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,this._el_58,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'By Name',(null as any));
    this._text_62 = this.renderer.createText(this._el_58,'\n        ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,this._el_58,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'By Votes',(null as any));
    this._text_65 = this.renderer.createText(this._el_58,'\n      ',(null as any));
    this._text_66 = this.renderer.createText(this._el_56,'\n\n      ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_56,'div',new import3.InlineArray2(2,'class','btn-group btn-group-sm'),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'\n        ',(null as any));
    this._el_69 = import3.createRenderElement(this.renderer,this._el_67,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'All',(null as any));
    this._text_71 = this.renderer.createText(this._el_67,'\n        ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_67,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Beginner',(null as any));
    this._text_74 = this.renderer.createText(this._el_67,'\n        ',(null as any));
    this._el_75 = import3.createRenderElement(this.renderer,this._el_67,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'Intermediate',(null as any));
    this._text_77 = this.renderer.createText(this._el_67,'\n        ',(null as any));
    this._el_78 = import3.createRenderElement(this.renderer,this._el_67,'button',new import3.InlineArray2(2,'class','btn btn-default'),(null as any));
    this._text_79 = this.renderer.createText(this._el_78,'Advanced',(null as any));
    this._text_80 = this.renderer.createText(this._el_67,'\n      ',(null as any));
    this._text_81 = this.renderer.createText(this._el_56,'\n    ',(null as any));
    this._text_82 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._el_83 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'\n      ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_83,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'Add Session',(null as any));
    this._text_87 = this.renderer.createText(this._el_83,'\n    ',(null as any));
    this._text_88 = this.renderer.createText(this._el_48,'\n  ',(null as any));
    this._text_89 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._anchor_90 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_90 = new import10.ViewContainer(90,0,this,this._anchor_90);
    this._TemplateRef_90_5 = new import15.TemplateRef_(this,90,this._anchor_90);
    this._NgIf_90_6 = new import11.Wrapper_NgIf(this._vc_90.vcRef,this._TemplateRef_90_5);
    this._text_91 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._anchor_92 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_92 = new import10.ViewContainer(92,0,this,this._anchor_92);
    this._TemplateRef_92_5 = new import15.TemplateRef_(this,92,this._anchor_92);
    this._NgIf_92_6 = new import11.Wrapper_NgIf(this._vc_92.vcRef,this._TemplateRef_92_5);
    this._text_93 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_uppercase_0 = new import12.UpperCasePipe();
    this._pipe_uppercase_0_0 = import3.pureProxy1(this._pipe_uppercase_0.transform.bind(this._pipe_uppercase_0));
    this._pipe_date_1 = new import13.DatePipe(this.parentView.injectorGet(import16.LOCALE_ID,this.parentIndex));
    this._pipe_date_1_0 = import3.pureProxy2(this._pipe_date_1.transform.bind(this._pipe_date_1));
    this._pipe_currency_2 = new import14.CurrencyPipe(this.parentView.injectorGet(import16.LOCALE_ID,this.parentIndex));
    this._pipe_currency_2_0 = import3.pureProxy3(this._pipe_currency_2.transform.bind(this._pipe_currency_2));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_60,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_60));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_63,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_63));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_69,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_69));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_72,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_72));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_75,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_75));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_78,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_78));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_85,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_85));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._anchor_90,
      this._text_91,
      this._anchor_92,
      this._text_93
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (90 === requestNodeIndex))) { return this._TemplateRef_90_5; }
    if (((token === import17.NgIf) && (90 === requestNodeIndex))) { return this._NgIf_90_6.context; }
    if (((token === import15.TemplateRef) && (92 === requestNodeIndex))) { return this._TemplateRef_92_5; }
    if (((token === import17.NgIf) && (92 === requestNodeIndex))) { return this._NgIf_92_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_90_0_0:boolean = !this.context.addMode;
    this._NgIf_90_6.check_ngIf(currVal_90_0_0,throwOnChange,false);
    this._NgIf_90_6.ngDoCheck(this,this._anchor_90,throwOnChange);
    const currVal_92_0_0:any = this.context.addMode;
    this._NgIf_92_6.check_ngIf(currVal_92_0_0,throwOnChange,false);
    this._NgIf_92_6.ngDoCheck(this,this._anchor_92,throwOnChange);
    this._vc_90.detectChangesInNestedViews(throwOnChange);
    this._vc_92.detectChangesInNestedViews(throwOnChange);
    const currVal_100:any = ((this.context.event == null)? (null as any): this.context.event.imageUrl);
    if (import3.checkBinding(throwOnChange,this._expr_100,currVal_100)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_100));
      this._expr_100 = currVal_100;
    }
    const currVal_101:any = ((this.context.event == null)? (null as any): this.context.event.name);
    if (import3.checkBinding(throwOnChange,this._expr_101,currVal_101)) {
      this.renderer.setElementProperty(this._el_2,'alt',currVal_101);
      this._expr_101 = currVal_101;
    }
    valUnwrapper.reset();
    const currVal_102:any = import3.inlineInterpolate(1,'',valUnwrapper.unwrap(import3.castByValue(this._pipe_uppercase_0_0,this._pipe_uppercase_0.transform)(((this.context.event == null)? (null as any): this.context.event.name))),' ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_102,currVal_102))) {
      this.renderer.setText(this._text_9,currVal_102);
      this._expr_102 = currVal_102;
    }
    valUnwrapper.reset();
    const currVal_105:any = import3.inlineInterpolate(1,' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_date_1_0,this._pipe_date_1.transform)(((this.context.event == null)? (null as any): this.context.event.date),'shortDate')),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_105,currVal_105))) {
      this.renderer.setText(this._text_20,currVal_105);
      this._expr_105 = currVal_105;
    }
    const currVal_108:any = import3.inlineInterpolate(1,' ',((this.context.event == null)? (null as any): this.context.event.time),'');
    if (import3.checkBinding(throwOnChange,this._expr_108,currVal_108)) {
      this.renderer.setText(this._text_25,currVal_108);
      this._expr_108 = currVal_108;
    }
    valUnwrapper.reset();
    const currVal_109:any = import3.inlineInterpolate(1,' ',valUnwrapper.unwrap(import3.castByValue(this._pipe_currency_2_0,this._pipe_currency_2.transform)(((this.context.event == null)? (null as any): this.context.event.price),'USD',true)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_109,currVal_109))) {
      this.renderer.setText(this._text_30,currVal_109);
      this._expr_109 = currVal_109;
    }
    const currVal_112:any = import3.inlineInterpolate(1,'\n        ',((this.context.event == null)? (null as any): ((this.context.event.location == null)? (null as any): this.context.event.location.address)),'');
    if (import3.checkBinding(throwOnChange,this._expr_112,currVal_112)) {
      this.renderer.setText(this._text_40,currVal_112);
      this._expr_112 = currVal_112;
    }
    const currVal_113:any = import3.inlineInterpolate(2,'\n        ',((this.context.event == null)? (null as any): ((this.context.event.location == null)? (null as any): this.context.event.location.city)),', ',((this.context.event == null)? (null as any): ((this.context.event.location == null)? (null as any): this.context.event.location.country)),'\n      ');
    if (import3.checkBinding(throwOnChange,this._expr_113,currVal_113)) {
      this.renderer.setText(this._text_42,currVal_113);
      this._expr_113 = currVal_113;
    }
    const currVal_114:any = (this.context.sortBy === 'name');
    if (import3.checkBinding(throwOnChange,this._expr_114,currVal_114)) {
      this.renderer.setElementClass(this._el_60,'active',currVal_114);
      this._expr_114 = currVal_114;
    }
    const currVal_115:any = (this.context.sortBy === 'votes');
    if (import3.checkBinding(throwOnChange,this._expr_115,currVal_115)) {
      this.renderer.setElementClass(this._el_63,'active',currVal_115);
      this._expr_115 = currVal_115;
    }
    const currVal_116:any = (this.context.filterBy === 'all');
    if (import3.checkBinding(throwOnChange,this._expr_116,currVal_116)) {
      this.renderer.setElementClass(this._el_69,'active',currVal_116);
      this._expr_116 = currVal_116;
    }
    const currVal_117:any = (this.context.filterBy === 'beginner');
    if (import3.checkBinding(throwOnChange,this._expr_117,currVal_117)) {
      this.renderer.setElementClass(this._el_72,'active',currVal_117);
      this._expr_117 = currVal_117;
    }
    const currVal_118:any = (this.context.filterBy === 'intermediate');
    if (import3.checkBinding(throwOnChange,this._expr_118,currVal_118)) {
      this.renderer.setElementClass(this._el_75,'active',currVal_118);
      this._expr_118 = currVal_118;
    }
    const currVal_119:any = (this.context.filterBy === 'advanced');
    if (import3.checkBinding(throwOnChange,this._expr_119,currVal_119)) {
      this.renderer.setElementClass(this._el_78,'active',currVal_119);
      this._expr_119 = currVal_119;
    }
  }
  destroyInternal():void {
    this._vc_90.destroyNestedViews();
    this._vc_92.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 90)) { return new View_EventDetailsComponent1(this.viewUtils,this,90,this._anchor_90,this._vc_90); }
    if ((nodeIndex == 92)) { return new View_EventDetailsComponent2(this.viewUtils,this,92,this._anchor_92,this._vc_92); }
    return (null as any);
  }
  handleEvent_60(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.sortBy = 'name')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_63(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.sortBy = 'votes')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_69(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'all')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_72(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'beginner')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_75(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'intermediate')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_78(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.filterBy = 'advanced')) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_85(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addSession()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_EventDetailsComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import19.SessionListComponent>;
  _SessionListComponent_0_3:import20.Wrapper_SessionListComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_EventDetailsComponent1,renderType_EventDetailsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'session-list',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import20.View_SessionListComponent0(this.viewUtils,this,0,this._el_0);
    this._SessionListComponent_0_3 = new import20.Wrapper_SessionListComponent(this.parentView.parentView.injectorGet(import21.AuthService,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import22.VoterService,this.parentView.parentIndex));
    this.compView_0.create(this._SessionListComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.SessionListComponent) && (0 === requestNodeIndex))) { return this._SessionListComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = ((this.parentView.context.event == null)? (null as any): this.parentView.context.event.sessions);
    this._SessionListComponent_0_3.check_sessions(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.filterBy;
    this._SessionListComponent_0_3.check_filterBy(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = this.parentView.context.sortBy;
    this._SessionListComponent_0_3.check_sortBy(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = ((this.parentView.context.event == null)? (null as any): this.parentView.context.event.id);
    this._SessionListComponent_0_3.check_eventId(currVal_0_0_3,throwOnChange,false);
    this._SessionListComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_EventDetailsComponent2 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import23.CreateSessionComponent>;
  _CreateSessionComponent_0_3:import24.Wrapper_CreateSessionComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_EventDetailsComponent2,renderType_EventDetailsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'create-session',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import24.View_CreateSessionComponent0(this.viewUtils,this,0,this._el_0);
    this._CreateSessionComponent_0_3 = new import24.Wrapper_CreateSessionComponent();
    this.compView_0.create(this._CreateSessionComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'saveNewSession',(null as any),'cancelAddSession',(null as any)),this.eventHandler(this.handleEvent_0));
    this._CreateSessionComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.CreateSessionComponent) && (0 === requestNodeIndex))) { return this._CreateSessionComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CreateSessionComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CreateSessionComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'saveNewSession')) {
      const pd_sub_0:any = ((<any>this.parentView.context.saveNewSession($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'cancelAddSession')) {
      const pd_sub_1:any = ((<any>this.parentView.context.cancelAddSession()) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}