/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.votingWidgetContainer[_ngcontent-%COMP%] {\r\n  padding-left:24px;\r\n}\r\n\r\n.votingWidget[_ngcontent-%COMP%] {\r\n  height: 64px;\r\n  padding-top: 7px;\r\n  border-radius: 21px;\r\n}\r\n\r\n.votingButton[_ngcontent-%COMP%] {\r\n  margin-left: -7px;\r\n  margin-top: 1px;\r\n  cursor:pointer;\r\n}\r\n\r\n.votingButton[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] {\r\n  color: white;\r\n}\r\n\r\n.badge-inverse[_ngcontent-%COMP%] {\r\n  background-color: #fff;\r\n  color: #4e5d6c;\r\n}\r\n\r\n.votingCount[_ngcontent-%COMP%] {\r\n  margin-left: -11px;\r\n  margin-top: 1px;\r\n  font-weight: bold;\r\n  font-size: 14px;\r\n}'];